/* =========================================================
   MASTERCARD DEVELOPERS API CATALOGUE — read from developer.mastercard.com/apis
   on 23 Sep 2026 (90 product cards) plus llms.txt (adds Insurance Programs).
   Each entry: [API name, slug, home product id]
   ========================================================= */
const APIS = [
 ["Account Services Catalogue","account-services-catalogue","asc"],
 ["Account to Account Commerce","account-to-account-commerce","a2acommerce"],
 ["Agent Suite for Merchants","agent-suite-for-merchants","agentsuite"],
 ["AML Account Risk","aml-account-risk-api","amlrisk"],
 ["Authentication Solutions","authentication-solutions","smartauth"],
 ["Automatic Billing Updater (ABU)","automatic-billing-updater-abu","abu"],
 ["Benefit Allocation Service","benefit-allocations","benefits"],
 ["Benefits Eligibility Service","benefits-eligibility","benefits"],
 ["Bill Pay","bill-pay","billpay"],
 ["Bill Payment Validator","bill-payment-validator","rpps"],
 ["BIN Lookup","bin-lookup","binlookup"],
 ["BS Creditor API","bs-creditor-api","betalingsservice"],
 ["Business Payment Controls","business-payment-controls","bpc"],
 ["Carbon Calculator","carbon-calculator","carbon"],
 ["Carbon Calculator Experience","carbon-calculator-experience","carbon"],
 ["Card on File Tokenization","card-on-file-tokenization","scof"],
 ["Click to Pay","click-to-pay","c2p"],
 ["Commercial Direct Payments","commercial-direct-payments","cdp"],
 ["Commercial Event Notifications","commercial-event-notifications","cen"],
 ["Community Pass","community-pass","communitypass"],
 ["Consumer Credit Analytics","consumer-credit-analytics","creditintel"],
 ["Currency Conversion Calculator","currency-conversion-calculator","fx"],
 ["Doconomy Aland Index","doconomy-aland-index","carbon"],
 ["Dynamic Yield","dynamic-yield","dy"],
 ["Ethoca Alerts","ethoca-alerts-for-merchants","ethocaalerts"],
 ["Ethoca Consumer Clarity for Merchants","ethoca-consumer-clarity-for-merchants","ethocacc"],
 ["Ethoca Consumer Clarity","ethoca-consumer-digital-experience","ethocacc"],
 ["First-Party Trust","first-party-trust","fpt"],
 ["Fraud and Loss Database (FLD)","fld-fraud-submission","fld"],
 ["Identity Insights for Accounts","identity-insights-for-accounts","mcidentity"],
 ["Identity Insights for Transactions","identity-insights-for-transactions","iift"],
 ["In Control for Commercial Payments","in-control-for-commercial-payments","incontrol"],
 ["India Online Dispute Resolution","india-online-dispute-resolution","mastercom"],
 ["Installments","installments","installments"],
 ["Location Intelligence","location-intelligence","places"],
 ["Mastercard Account Validation","mastercard-account-validation","acctval"],
 ["Mastercard Benefits & Experiences Portal","mastercard-benefits-and-experiences-portal","benefits"],
 ["Mastercard Cloud Commerce","cloud-commerce","taponphone"],
 ["Mastercard Commercial Connect API","commercial-connect-api","incontrol"],
 ["Mastercard Contactless Reader SDK","tap-on-phone-terminal-sdk","taponphone"],
 ["Mastercard Cross-Border Services","cross-border-services","xborder"],
 ["Mastercard Cyber and Payment Threat Solutions","mastercard-cyber-and-payment-threat-solutions","mcti"],
 ["Mastercard Developer Hub for FDX APIs","fdx-developer-hub","fdxhub"],
 ["Mastercard Direct Services","direct-service-api","directservices"],
 ["Mastercard Donate","mastercard-donate","donate"],
 ["Mastercard Easy Savings Program","mastercard-easy-savings-program","easysavings"],
 ["Mastercard Gateway","mastercard-gateway","gateway"],
 ["Mastercard Installments at Checkout","mastercard-installments-at-checkout","installments"],
 ["Mastercard Insurance Programs","","insurance"],
 ["Mastercard Loyalty Management","mastercard-loyalty-management","loyalty"],
 ["Mastercard Loyalty Promotions","mastercard-loyalty-promotions","loyalty"],
 ["Mastercard Merchant Presented QR: SRC","mastercard-merchant-presented-qr-src","qr"],
 ["Mastercard Move","move","move"],
 ["Mastercard Open Finance Theming API","mastercard-ob-theming","ofus"],
 ["Mastercard Pay with Rewards","mastercard-pay-with-rewards","loyalty"],
 ["Mastercard Processing","mastercard-processing","processing"],
 ["Mastercard QR","mastercard-qr","qr"],
 ["Mastercard Redemption Services","mastercard-redemption-services","loyalty"],
 ["Mastercard Send","mastercard-send","send"],
 ["Mastercard Sonic Branding","mastercard-sonic-branding","sonic"],
 ["Mastercard Threat Intelligence","mastercard-threat-intelligence","mcti"],
 ["Mastercard Track Business Payment Service","mastercard-track-business-payment-service","trackbps"],
 ["Mastercard Virtual Card Tokens","mastercard-virtual-card-tokens","vctokens"],
 ["Mastercard Wallet Services","mastercard-wallet-services","walletservices"],
 ["Mastercard Identity Check","identity-check","idcheck"],
 ["Mastercom","mastercom","mastercom"],
 ["MATCH Pro","match","matchpro"],
 ["MCBP MP SDK","mobile-payments-sdk","mcbp"],
 ["MDES","mdes","mdes"],
 ["Merchant Cloud","merchant-cloud","merchantcloud"],
 ["Merchant Identifier","merchant-identifier","merchantid"],
 ["Mexico Insights","mexico-insights","spendingpulse"],
 ["Offers for Publishers","personalized-offers","offers"],
 ["Offers Merchant Content","eop-admin","offers"],
 ["Onboard Risk Check","onboard-risk-check","orc"],
 ["Open Finance (Europe)","open-finance-europe","ofeu"],
 ["Open Finance (US & AU)","open-finance","ofus"],
 ["Pay by Account","pay-by-account","a2astack"],
 ["Payment Account Management","payment-account-management","asi"],
 ["Payment Account Reference Inquiry","payment-account-reference-inquiry","par"],
 ["Places","places","places"],
 ["Priceless Cities","priceless-cities","priceless"],
 ["Priceless Platform","priceless-platform","priceless"],
 ["Priceless Specials","priceless-specials","priceless"],
 ["RiskRecon API","riskrecon","riskrecon"],
 ["Small Business Credit Analytics","small-business-credit-analytics","creditintel"],
 ["Subscription Controls","subscription-controls","minna"],
 ["Test & Learn","test-and-learn","testlearn"],
 ["Token Authentication Service (TAS)","token-authentication-service","tas"],
 ["Track Search","track-search","trackbps"],
 ["Transaction Notifications","transaction-notifications","txnnotif"],
];

