const USERS = {
  iss:"Issuers & banks", acq:"Acquirers & PSPs", mer:"Merchants", fin:"Fintechs & wallets",
  corp:"Corporates & SMEs", gov:"Governments & public sector", con:"Consumers", ai:"AI agents & machines"
};
const LC = {before:"Before the transaction", checkout:"At checkout", auth:"Authorisation", settle:"Clearing & settlement", after:"After the transaction", beyond:"Beyond the transaction"};
const ST = {active:"Active", new:"New in 2025–26", flux:"In flux", unconf:"Unconfirmed", retired:"Retired / divested"};
const OR = {B:"Built in-house", A:"Acquired"};
const REV = {net:"Payment network", sec:"VAS · Security solutions", eng:"VAS · Consumer acquisition & engagement", ins:"VAS · Business & market insights", dig:"VAS · Digital & authentication", proc:"VAS · Processing & gateway", oth:"VAS · Other (ACH/RTP, bill pay, cross-border, open finance)", na:"Not a revenue line"};
const DIV = {core:"Core / Consumer Payments", cnpf:"Commercial & New Payment Flows", svc:"Services", corp:"Corporate / cross-cutting"};
const APIF = {yes:"Has a Mastercard Developers API", no:"No public API"};



function P(id,n,d,x){ return Object.assign({id,n,d,s:[],lc:"beyond",st:"active",o:"B",src:[]},x||{}); }
const M="https://www.mastercard.com", D="https://developer.mastercard.com", I="https://investor.mastercard.com";

const LAYERS = [
 {id:"U", name:"Users", analogy:"the ecosystem the OS serves", color:"--lu", users:true,
  desc:"Eight kinds of user, including a new one. Most assets serve several; the Customer lens shows which.",
  tiles: Object.keys(USERS).map(k=>({id:"u-"+k, name:USERS[k], user:k, products:[]}))},

 {id:"L5", name:"Access", analogy:"shell · SDKs · app store", color:"--l5",
  desc:"How customers and developers plug in: the API platform, the acceptance and issuing platforms, and the programmes that onboard partners. Reported inside Value-added services as Processing & gateway.",
  tiles:[
   {id:"5.1", name:"Developers & APIs", blurb:"One front door for the whole OS.", div:"core", rev:"proc", products:[
    P("developers","Mastercard Developers","developer.mastercard.com: the public API platform — 91 API products in the catalogue as at 23 September 2026, each with sandbox, reference apps and OAuth or MTLS access. Every one is mapped to its home tile on this map (open this tile for the full catalogue).",{s:["fin","mer","acq","iss","ai"],lc:"before",src:[["Mastercard Developers — API catalogue",D+"/apis"],["Platform index (llms.txt)",D+"/llms.txt"]]}),
   ]},
   {id:"5.2", name:"Acceptance platforms", blurb:"Merchant and acquirer side.", div:"core", rev:"proc", products:[
    P("merchantcloud","Mastercard Merchant Cloud","Unified acceptance stack: tokenisation, gateway, Click to Pay, fraud and identity, the Payment Optimization Platform and Agent Pay; 240+ acquirers, 35+ payment types.",{s:["acq","mer","fin"],lc:"checkout",st:"new",ay:"Oct 2025",src:[["Launch press release, Oct 2025",M+"/us/en/news-and-trends/press/2025/october/Mastercard-Merchant-Cloud-simplify-and-support-commerce-growth-in-global-acceptance-ecosystem.html"]]}),
    P("gateway","Mastercard Gateway (MPGS)","Omnichannel payment gateway (MiGS → MPGS → Gateway); increasingly positioned as a component inside Merchant Cloud.",{s:["acq","mer"],lc:"checkout",o:"A",ay:"2010",at:"DataCash",src:[["Mastercard Gateway",M+"/gateway.html"]]}),
   ]},
   {id:"5.3", name:"Issuing platforms", blurb:"Issuer and fintech side.", div:"core", rev:"proc", products:[
    P("processing","Mastercard Processing","Issuer processing-as-a-service (Core and Debit APIs); Thought Machine partnership 2024; includes the former Nets issuer-processing business.",{s:["iss","fin"],lc:"before",o:"B",note:"Expanded by acquisition of Nets' processing business (2021).",src:[["Mastercard Processing — Developers",D+"/product/mastercard-processing/"],["Thought Machine partnership, Jun 2024",M+"/us/en/news-and-trends/press/2024/june/mastercard-and-european-cloud-native-issuer-processor-leverages-mastercard-cloud-edge-proving-seamless-payment-experience.html"]]}),
    P("cloudedge","Mastercard Cloud Edge","Cloud connectivity to the network with up to 4× faster onboarding; live in APAC, US, Canada and select EEMEA/LatAm markets; certified partners include Paymentology, Deserve and Clowd9.",{s:["iss","acq","fin"],lc:"before",st:"new",ay:"Jun 2025",src:[["Cloud Edge press release, Jun 2025",M+"/news/ap/en/newsroom/press-releases/en/2025/mastercard-onboards-customers-up-to-four-times-faster-with-cloud-edge/"]]}),
    P("productexpress","Product Express — Card Issuance","Fast-track card-programme launch for fintechs; formerly branded Fintech Express.",{s:["fin"],lc:"before",st:"flux",note:"Renamed from Fintech Express; current page is titled Product Express.",src:[["Product Express page",M+"/global/en/business/industry-segment/fintech/program/product-express-card-issuance.html"]]}),
    P("engage","Mastercard Engage","Marketplace of 170+ vetted enablement partners; 500m+ cards run on an Engage partner.",{s:["fin","iss"],lc:"before",src:[["Mastercard Engage",M+"/us/en/business/industry-segment/fintech/program/engage.html"]]}),
   ]},
   {id:"5.4", name:"Programmes & innovation", blurb:"How partners get in early.", div:"core", rev:"na", products:[
    P("startpath","Start Path","Startup engagement programme since 2014: 500+ startups from 60+ countries; an Emerging Fintech track added 11 startups in September 2025.",{s:["fin"],src:[["Start Path",M+"/us/en/innovation/partner-with-us/start-path.html"],["Emerging Fintech cohort, Sep 2025",M+"/us/en/news-and-trends/press/2025/september/mastercard-welcomes-11-startups-to-start-path%E2%80%99s-emerging-fintech-program.html"]]}),
    P("partnerprog","Partner Advantage Program & Circle of Honor","Partner and recognition programmes listed on Mastercard's business site.",{s:["fin","acq"],src:[["Mastercard for business",M+"/us/en/business.html"]]}),
   ]},
  ]},

 {id:"L4", name:"Solutions", analogy:"applications", color:"--l4",
  desc:"Value-added services sold to customers and usable whether or not the payment ran on Mastercard. About 31% of FY2025 net revenue, growing +23% against +12% for the network — and mostly acquired.",
  tiles:[
   {id:"4.1", name:"Security Solutions", blurb:"Identity, cyber and financial crime for enterprises.", div:"svc", rev:"sec", products:[
    P("mcidentity","Mastercard Identity (Ekata)","Identity Insights for Accounts, Identity Review 360 and Identity Authentication: global identity signals for account opening and KYC. The Ekata brand now redirects to Mastercard Identity.",{s:["mer","fin","iss"],lc:"before",st:"flux",o:"A",ay:"2021",at:"Ekata (~$850m)",src:[["Mastercard Identity hub",M+"/us/en/business/cybersecurity-fraud-prevention/identity.html"]]}),
    P("nudata","NuData Security / NuDetect","Passive behavioural biometrics that separate humans from bots and account takeover without adding friction.",{s:["mer","iss","fin"],lc:"before",o:"A",ay:"2017",at:"NuData Security",src:[["nudatasecurity.com","https://nudatasecurity.com/"]]}),
    P("mcid","Mastercard ID","Digital-identity service: UK-certified digital ID provider; healthcare patient identification.",{s:["gov","con","mer"],lc:"before",src:[["UK digital ID certification, 2023",M+"/news/europe/en-uk/newsroom/press-releases/en-gb/2023/mastercard-certified-in-the-uk-as-a-trusted-provider-of-digital-id-services/"]]}),
    P("trustcenter","Trust Center","Free cybersecurity education and tools for small businesses, with an annual SMB cybersecurity study.",{s:["corp"],src:[["Trust Center",M+"/us/en/business/industry-segment/small-medium-business/trust-center.html"]]}),
    P("riskrecon","RiskRecon","Continuous third-party and vendor cyber-risk ratings from external scanning — no vendor cooperation needed.",{s:["corp","iss","acq"],o:"A",ay:"2019",at:"RiskRecon (closed 2020)",src:[["TechCrunch on the acquisition","https://techcrunch.com/2019/12/23/mastercard-acquires-security-assessment-startup-riskrecon"]]}),
    P("cybersuite","Cyber Secure · Cyber Quant · Cyber Front · Cyber Crisis Exercise · Cyber Insights","Portfolio cyber risk, dollarised risk quantification (Gartner Hype Cycle 2025), attack simulation, tabletop exercises and strategic threat intelligence — delivered on the RiskRecon platform.",{s:["iss","acq","corp"],src:[["Cyber Quant",M+"/us/en/business/cybersecurity-fraud-prevention/risk-decisioning/solutions/cyber-quant.html"],["Cyber Front launch, 2022","https://newsroom.mastercard.com/news/press/2022/may/another-arrow-in-the-quiver-mastercard-strengthens-cybersecurity-consulting-practice-with-new-cyber-front-threat-simulation-platform/"]]}),
    P("sysrisk","Systemic Risk Assessment & Third Party Risk Management","Concentration and third-party risk across an issuer's or acquirer's portfolio.",{s:["iss","acq"],src:[["Systemic Risk Assessment",M+"/us/en/business/cybersecurity-fraud-prevention/cybersecurity/systemic-risk-assessment.html"]]}),
    P("baffin","Threat Protection (Baffin Bay Networks)","Cloud-native DDoS, bot and malicious-traffic protection.",{s:["corp","iss","mer"],o:"A",ay:"2023",at:"Baffin Bay Networks",src:[["Investor release, Mar 2023",I+"/investor-news/investor-news-details/2023/Mastercard-Strengthens-Customer-Security-With-New-AI-Cyber-Shield/default.aspx"]]}),
    P("recfut","Recorded Future","Intelligence Cloud / Intelligence Graph indexing 1m+ sources, with Payment Fraud Intelligence and Identity Intelligence modules. Mastercard's largest acquisition.",{s:["corp","gov","iss"],o:"A",ay:"Dec 2024",at:"Recorded Future ($2.65bn)",src:[["Acquisition close, Dec 2024","https://www.businesswire.com/news/home/20241220165251/en/Mastercard-Finalizes-Acquisition-of-Recorded-Future"],["Payment Fraud Intelligence","https://www.recordedfuture.com/products/payment-fraud-intelligence"]]}),
    P("mcti","Mastercard Threat Intelligence","First fraud-plus-cyber product built on Recorded Future: real-time card-testing detection, digital-skimming intelligence and merchant threat assessments.",{s:["iss","acq"],lc:"before",st:"new",ay:"Oct 2025",src:[["Launch press release, Oct 2025",M+"/us/en/news-and-trends/press/2025/october/Mastercard-introduces-first-ever-threat-intelligence-solution.html"]]}),
    P("a2aprotect","Consumer Fraud Risk → A2A Protect","AI scam scoring on real-time payment rails (UK APP fraud −20% in 2024), now a Prevent / Protect / Recover suite used by 15 UK banks.",{s:["iss"],lc:"auth",st:"new",ay:"2023 → 2025",src:[["A2A Protect, 2025",M+"/news/europe/en-uk/newsroom/press-releases/en-gb/2025/prevent-protect-and-recover-mastercard-strengthens-trust-in-account-to-account-payments/"]]}),
    P("scamprotect","Scam Protect","Umbrella brand (2024) across Mastercard's scam-fighting tools — a portfolio name, not a single product.",{s:["iss","con"],src:[["Scam Protect","https://b2b.mastercard.com/scam-protect"]]}),
    P("trace","TRACE","AML service that surfaces newly created money-mule accounts (100+ a month); launched for Asia Pacific in February 2025.",{s:["iss"],lc:"after",st:"new",ay:"Feb 2025",src:[["TRACE launch, Feb 2025",M+"/us/en/news-and-trends/press/2025/february/mastercard-launches-anti-money-laundering-service-trace-to-combat-financial-crime-in-asia-pacific.html"]]}),
    P("cryptosecure","Crypto Secure","Issuer dashboard of VASP risk and crypto spending so low-risk crypto-linked transactions can be approved.",{s:["iss"],lc:"auth",ay:"2022",note:"Built on CipherTrace data.",src:[["Crypto Secure",M+"/us/en/business/cybersecurity-fraud-prevention/crypto-secure.html"]]}),
    P("amlrisk","AML Account Risk","Augments issuers' anti-money-laundering processes by flagging potential laundering at the individual account (PAN) level.",{s:["iss"],lc:"after",src:[["AML Account Risk — Developers",D+"/product/aml-account-risk-api"]]}),
    P("ciphertrace","CipherTrace","Crypto intelligence: compliance monitoring, risk assessment and investigations. The Armada, Inspector and Sentry products were shut down in March 2024.",{s:["fin","gov","iss"],st:"flux",o:"A",ay:"2021",at:"CipherTrace",src:[["Fortune on the 2024 shutdown","https://fortune.com/crypto/2024/03/13/mastercard-ciphertrace-blockchain-analytics-chainalysis-bitcoin-fog/"]]}),
   ]},
   {id:"4.2", name:"Consumer Acquisition & Engagement", blurb:"Personalisation, marketing, loyalty, benefits.", div:"svc", rev:"eng", products:[
    P("dy","Dynamic Yield / Experience OS","AI personalisation platform — Shopping Muse, Experience OS Agents, Experience APIs, Experience Search; 8× Gartner MQ leader; 80m+ personalised sessions a day.",{s:["mer","corp"],o:"A",ay:"2022",at:"Dynamic Yield (from McDonald's)",src:[["Dynamic Yield product page",M+"/us/en/business/consumer-acquisition-and-engagement/personalization/dynamic-yield.html"],["Close of acquisition, 2022",I+"/investor-news/investor-news-details/2022/Mastercard-Strengthens-Consumer-Engagement-Services-With-Close-of-Dynamic-Yield-Acquisition/default.aspx"]]}),
    P("mktsvc","Mastercard Marketing Services","Full-funnel lifecycle marketing: Acquisition, Engagement and a Performance Engine for optimisation.",{s:["iss","mer"],src:[["Marketing Services",M+"/us/en/business/consumer-acquisition-and-engagement/marketing-services.html"]]}),
    P("audhub","Marketing Audience Hub","Audience identification, media optimisation and campaign personalisation; the successor to the 'Mastercard Audiences' name.",{s:["iss","mer"],st:"flux",src:[["Marketing Audience Hub",M+"/us/en/business/consumer-acquisition-and-engagement/personalization/solutions/marketing-audience-hub.html"]]}),
    P("commedia","Mastercard Commerce Media","Retail-media network connecting advertisers and publishers: 500m+ permissioned consumers, 25,000+ merchant advertisers.",{s:["mer","iss"],st:"new",ay:"Oct 2025",src:[["Launch press release, Oct 2025",M+"/global/en/news-and-trends/press/2025/october/powering-smarter-and-more-personal-advertising-with-mastercard-commerce-media.html"]]}),
    P("loyalty","Loyalty Solutions","Rewards, Pay Rewards, Global Redemption Suite, Promotions and Digital Disbursements; 1.3tn loyalty points under management.",{s:["iss","mer","con"],lc:"after",src:[["Consumer Acquisition & Engagement",M+"/us/en/business/consumer-acquisition-and-engagement.html"]]}),
    P("priceless","Priceless & cardholder benefits","Priceless Experiences, Discounts and Surprises (Priceless Africa, June 2026), Travel & Lifestyle Services, Airport Experiences via LoungeKey, and tiered card benefits.",{s:["con","iss"],lc:"after",src:[["Priceless","https://www.priceless.com/about"],["Priceless Africa launch, Jun 2026",M+"/news/eemea/en/newsroom/press-releases/en/2026/june-2026/mastercard-launches-priceless-africa-on-priceless-com-unlocking-a-curated-travel-experience-across-nine-iconic-destinations/"]]}),
    P("offers","Offers platform","Merchant-funded offers distributed to cardholders through issuer and publisher apps; merchants and aggregators push profiles, offers and images into the platform.",{s:["iss","mer","fin"],lc:"after",src:[["Offers for Publishers — Developers",D+"/product/personalized-offers"],["Offers Merchant Content — Developers",D+"/product/eop-admin"]]}),
    P("benefits","Card benefits services","Issuer tooling to allocate, check eligibility for and let cardholders personalise their card benefits — Benefit Allocation, Benefits Eligibility and the Benefits & Experiences Portal.",{s:["iss","con"],lc:"after",src:[["Benefits & Experiences Portal — Developers",D+"/product/mastercard-benefits-and-experiences-portal"]]}),
    P("insurance","Mastercard Insurance Programs","Card-linked insurance programmes exposed to issuers through the Developers catalogue (listed in the platform index; no separate product page was readable).",{s:["iss","con"],lc:"after",st:"unconf",src:[["Mastercard Developers — llms.txt index",D+"/llms.txt"]]}),
    P("carbon","Carbon Calculator (Doconomy Åland Index)","Transaction-level carbon-footprint scoring, consumer-facing footprint and offset experiences, and Doconomy's Åland Index sustainability services; a China file-based variant exists.",{s:["iss","fin","con"],lc:"after",src:[["Carbon Calculator — Developers",D+"/product/carbon-calculator"],["Doconomy Åland Index — Developers",D+"/product/doconomy-aland-index"]]}),
    P("sessionm","SessionM","Loyalty and engagement platform acquired in 2019 — sold to Capillary Technologies in February 2026.",{s:["mer"],st:"retired",o:"A",ay:"2019 → divested Feb 2026",at:"SessionM",src:[["Capillary announcement, Feb 2026","https://www.capillarytech.com/blog/capillary-technologies-acquires-sessionm-from-mastercard/"]]}),
    P("ifonly","IfOnly","Experiences marketplace folded into Priceless; shut down in August 2020.",{s:["con"],st:"retired",o:"A",ay:"~2019 → closed 2020",at:"IfOnly",src:[["TechCrunch, Aug 2020","https://techcrunch.com/2020/08/24/mastercard-acquired-and-shut-down-ifonly-an-experiences-marketplace-hit-by-covid-19/"]]}),
   ]},
   {id:"4.3", name:"Insights & Intelligence", blurb:"Analytics and research on network data.", div:"svc", rev:"ins", products:[
    P("testlearn","Test & Learn","Controlled-experimentation platform for retailers and financial institutions.",{s:["mer","iss","corp"],o:"A",ay:"2015",at:"Applied Predictive Technologies ($600m)",src:[["APT acquisition, 2015",I+"/investor-news/investor-news-details/2015/MasterCard-Announces-Acquisition-of-Applied-Predictive-Technologies/default.aspx"]]}),
    P("spendingpulse","SpendingPulse & market insights","SpendingPulse, Market Share, Market Trends, Macro360 and Forecasting & Scenario Planning: macro and sector spending insight.",{s:["mer","gov","iss"],src:[["SpendingPulse",M+"/us/en/business/insights-intelligence/economic-market-insights/solutions/spendingpulse.html"]]}),
    P("places","Places & location analytics","Places, Geo Insights, Shopper Intelligence, Merchant Insights, Tourism Insights, Ad Insights and ATM Locations.",{s:["mer","gov","corp"],src:[["Economic & Market Insights",M+"/us/en/business/insights-intelligence/economic-market-insights.html"]]}),
    P("mei","Mastercard Economics Institute","In-house economists publishing macro and consumer-spending research; also the Mastercard Research Center.",{s:["gov","corp","iss"],src:[["Economics Institute","https://www.mastercardservices.com/en/resources/economics-institute"]]}),
    P("portfolio","Portfolio Optimizer & issuer tools","Portfolio Optimizer, Portfolio Advisor, Cards Lab, Smart Leads, Pioneer and AI Ready.",{s:["iss"],src:[["Insights & Intelligence",M+"/global/en/business/insights-intelligence.html"]]}),
    P("intelcenter","Intelligence Centers","Mastercard Intelligence Center, Acquirer Intelligence Center and Acquiring Optimizer dashboards.",{s:["iss","acq"],src:[["Insights & Intelligence",M+"/global/en/business/insights-intelligence.html"]]}),
    P("creditintel","Credit Intelligence Solutions","Consumer and small-business credit analytics combining network and open-finance data.",{s:["iss","fin"],lc:"before",src:[["Q4 2025 earnings review",M+"/global/en/news-and-trends/stories/2026/earnings-review-q4-2025.html"]]}),
    P("cleanroom","Data Clean Room & Media Measurement","Privacy-preserving data collaboration and independent anonymisation. No product literally named 'Data Cloud' was found.",{s:["mer","iss"],src:[["Insights & Intelligence",M+"/global/en/business/insights-intelligence.html"]]}),
    P("opsintel","Operations Intelligence","Operational Reports, Transaction Investigator Plus, Learning Lab and Digital Safari.",{s:["iss","acq"],lc:"after",src:[["Insights & Intelligence",M+"/us/en/business/insights-intelligence.html"]]}),
   ]},
   {id:"4.4", name:"Advisors & Transformation", blurb:"Consulting, innovation and delivery.", div:"svc", rev:"ins", products:[
    P("advisors","Advisors & Transformation","Consulting arm (Advisory · Innovation · Deploy): ~4,000 consultants in 120+ countries. Lineage: Mastercard Advisors (2001) → Data & Services (2019) → Services (2024).",{s:["iss","acq","mer","corp","gov"],ay:"2001",src:[["Advisors & Transformation",M+"/us/en/business/insights-intelligence/advisors-transformation.html"]]}),
    P("practices","Consulting practices","Payments, Cyber & Enterprise Risk, Data Strategy & Management, AI & Advanced Analytics, Sustainability & Financial Inclusion, Future Tech.",{s:["iss","acq","mer","corp","gov"],src:[["AI & Advanced Analytics Consulting",M+"/global/en/business/insights-intelligence/mastercard-advisors/ai-and-advanced-analytics-consulting.html"]]}),
    P("digitallabs","Digital Labs, Strategy Insight, Sandbox as a Service","Innovation-as-a-service under the Mastercard Foundry umbrella: strategy and insight, design and prototype, execute and accelerate.",{s:["iss","fin","corp"],src:[["Digital Labs",M+"/us/en/innovation/build-with-us/digital-labs.html"]]}),
    P("managed","Managed services","A delivery model (managed fraud rules, managed cyber) rather than a branded product.",{s:["iss","mer"],st:"unconf",note:"Referenced as a delivery model and job family, not a distinct product."}),
   ]},
   {id:"4.5", name:"Commercial & B2B", blurb:"Buyer–supplier payments and controls.", div:"cnpf", rev:"oth", products:[
    P("trackbps","Mastercard Track Business Payment Service","Buyer–supplier network for invoice presentment, payment terms and working capital.",{s:["corp","iss"],lc:"checkout",ay:"2020",src:[["US launch, May 2020","https://www.businesswire.com/news/home/20200512005463/en/Mastercard-Track-Business-Payment-Service-Launches-in-the-U.S.-Brings-Efficiency-Gains-and-Faster-Access-to-Working-Capital-to-Suppliers-and-Buyers"]]}),
    P("trackip","Track Instant Pay","Virtual-card instant B2B payment inside accounts-payable workflows (Marqeta integration).",{s:["corp","iss","fin"],lc:"checkout",ay:"2022",src:[["Launch, Jan 2022","https://www.businesswire.com/news/home/20220120005082/en/Mastercard-Unveils-Next-Generation-Virtual-Card-Solution-for-Instant-B2B-Payments"]]}),
    P("incontrol","In Control & Commercial Connect API","Virtual card numbers and spend controls; single-API relaunch with Citi as first global issuer, July 2026.",{s:["iss","corp"],lc:"before",st:"new",o:"A",ay:"2009",at:"Orbiscom",src:[["Commercial Connect, Jul 2026",M+"/us/en/news-and-trends/press/2026/july/Mastercard-expands-virtual-card-platform.html"]]}),
    P("smartdata","Smart Data","Commercial-card expense reporting and reconciliation, embeddable in platforms such as Galileo.",{s:["corp","iss"],lc:"after",src:[["Smart Data",M+"/au/en/business/payments/commercial-payments/corporate-solutions/smart-data.html"]]}),
    P("receivables","Receivables Manager","Supplier-side virtual-card acceptance and reconciliation; globally available from July 2025.",{s:["corp","acq"],lc:"after",st:"new",ay:"2023 → global Jul 2025",src:[["Global expansion, Jul 2025",M+"/us/en/news-and-trends/press/2025/july/mastercard-accelerates-b2b-payment-automation-globally-with-acce.html"]]}),
    P("easysavings","Easy Savings","Small-business rebate programme tied to business cards.",{s:["corp","iss"],lc:"after",src:[["Easy Savings","https://www.mastercard.us/en-us/business/industry-segment/small-medium-business/easy-savings.html"]]}),
    P("bpc","Business Payment Controls","Configurable spending controls on real and virtual commercial cards with transaction-level reporting for reconciliation.",{s:["corp","iss"],lc:"auth",src:[["Business Payment Controls — Developers",D+"/product/business-payment-controls"]]}),
    P("cdp","Commercial Direct Payments","Automates B2B card payments end to end — buyer to supplier — to cut cost, complexity and risk.",{s:["corp","iss","acq"],lc:"checkout",src:[["Commercial Direct Payments — Developers",D+"/product/commercial-direct-payments"]]}),
    P("cen","Commercial Event Notifications","Rapid payment and token notifications for B2B payments so finance teams can reconcile accurately.",{s:["corp","iss"],lc:"after",src:[["Commercial Event Notifications — Developers",D+"/product/commercial-event-notifications"]]}),
    P("healthcare","Healthcare & embedded finance","Named focus areas of Commercial & New Payment Flows on Mastercard's commercial pages.",{s:["corp","fin"],src:[["Commercial payments",M+"/us/en/business/payments/commercial-payments.html"]]}),
   ]},
   {id:"4.6", name:"AI & agent applications", blurb:"Mastercard's 'AI' category — mostly cross-references.", div:"svc", rev:"ins", products:[
    P("agentsuite","Mastercard Agent Suite","Customisable AI agents for banks and merchants (product recommendation, conversational shopping), integrated with Agent Pay; includes the Developers Agent Toolkit.",{s:["iss","mer","corp"],st:"new",ay:"Jan 2026",rel:["agentpay","dipro","dy","practices","merchantcloud"],src:[["Launch press release, Jan 2026",M+"/global/en/news-and-trends/press/2026/january/mastercard-launches-agent-suite-to-ready-enterprises-for-a-new-e.html"]]}),
   ]},
  ]},

 {id:"L3", name:"Network services", analogy:"system services", color:"--l3",
  desc:"Services invoked around a payment on any rail: make the credential digital, prove who is paying, decide the risk, resolve what goes wrong, keep the account current — and, since 2025, let an AI agent do it.",
  tiles:[
   {id:"3.1", name:"Tokenisation & credentials", blurb:"Replace the card number.", div:"core", rev:"dig", products:[
    P("mdes","Mastercard Digital Enablement Service (MDES)","Core network tokenisation: replaces the PAN with device- or merchant-bound tokens for wallets, in-app, contactless and card-on-file.",{s:["iss","fin","mer"],lc:"before",src:[["MDES — Developers",D+"/product/mdes"]]}),
    P("scof","MDES for Merchants / Secure Card on File","Merchant and PSP tokenisation of stored credentials; live in 45 European countries by mid-2025.",{s:["mer","acq"],lc:"before",src:[["Secure Card on File",M+"/global/en/business/payments/commercial-payments/accept-payments/secure-card-on-file.html"]]}),
    P("tokenconnect","Token Connect & Pre-Digitization","Push-provisioning of tokens to merchants and wallets, and issuer- or token-requestor-initiated tokenisation flows.",{s:["iss","mer"],lc:"before",src:[["MDES Token Connect",D+"/mdes-token-connect/documentation/use-cases/push-to-merchant/"]]}),
    P("tas","Token Authentication Service (TAS)","Pairs a network token with OTP or passkey step-up inside Mastercard Gateway and Click to Pay. ('Token Authentication Framework' was not found as a product name.)",{s:["mer","acq"],lc:"checkout",src:[["TAS flow — Gateway docs",D+"/mastercard-gateway/documentation/security-and-fraud/authentication/token-auth-service/token-auth-service-flow/"]]}),
    P("onecred","Mastercard One Credential","One credential connected to debit, credit, prepaid and instalment funding with consumer-set preferences; partners Wio Bank, Marqeta, Lithic and Botim (Aug 2026).",{s:["iss","fin","con"],lc:"before",st:"new",ay:"2025",src:[["One Credential",M+"/global/en/business/payments/consumer-payments/next-gen-payments/mastercard-one-credential.html"]]}),
    P("digitalfirst","Digital First","End-to-end framework for instant digital issuance and a digital-native card experience; issuers saw +10% contactless and +8% tokenised transactions.",{s:["iss","fin"],lc:"before",ay:"2022",src:[["Digital First",M+"/global/en/business/payments/consumer-payments/next-gen-payments/digital-first.html"]]}),
    P("token2030","Tokenised e-commerce by 2030","Commitment (June 2024) to phase out manual card entry in European e-commerce by 2030; ~50% of European e-commerce transactions were tokenised by mid-2025. A goal, not a product.",{s:["iss","mer"],lc:"checkout",src:[["One-year update, Jun 2025","https://www.businesswire.com/news/home/20250603515548/en"]]}),
    P("vctokens","Mastercard Virtual Card Tokens","Tokenises browser-autofill card entries so saved cards in the browser are network tokens rather than PANs.",{s:["mer","fin","con"],lc:"checkout",src:[["Virtual Card Tokens — Developers",D+"/product/mastercard-virtual-card-tokens"]]}),
    P("walletservices","Mastercard Wallet Services","Fast contactless enablement and new use cases for wallet providers and banking apps that want to expand in digital payments.",{s:["fin","iss"],lc:"before",src:[["Wallet Services — Developers",D+"/product/mastercard-wallet-services"]]}),
    P("mcbp","MCBP MP SDK (Cloud-Based Payments)","SDK that simplifies building Mastercard Cloud-Based Payments wallet applications for Android and iOS.",{s:["fin","iss"],lc:"before",src:[["MCBP MP SDK — Developers",D+"/product/mobile-payments-sdk"]]}),
    P("par","Payment Account Reference Inquiry","Looks up the Payment Account Reference (PAR) for a PAN or MDES token where Mastercard is the BIN controller — linking tokens back to one account without exposing it.",{s:["mer","acq","iss"],lc:"after",src:[["PAR Inquiry — Developers",D+"/product/payment-account-reference-inquiry"]]}),
   ]},
   {id:"3.2", name:"Authentication & checkout", blurb:"Prove who is paying, without friction.", div:"core", rev:"dig", products:[
    P("idcheck","Mastercard Identity Check (EMV 3-D Secure)","Risk-based 3DS authentication, successor to SecureCode; 150+ data elements exchanged per authentication.",{s:["iss","mer","con"],lc:"checkout",src:[["Identity Check — Developers",D+"/product/identity-check/"]]}),
    P("smartauth","Smart Authentication · Identity Check Express · Stand-In RBA","Risk-based authentication targeting 90–95% frictionless decisions; a lighter flow launched in India (2019); Mastercard-performed RBA when the issuer's ACS is down.",{s:["iss"],lc:"checkout",src:[["Authentication",M+"/global/en/business/cybersecurity-fraud-prevention/identity/authentication.html"]]}),
    P("iift","Identity Insights for Transactions","Issuer–merchant data sharing at authorisation, including the Microsoft Dynamics 365 Fraud Protection partnership (+14% approvals). Formerly 'Digital Transaction Insights'.",{s:["iss","mer"],lc:"auth",st:"flux",src:[["Identity Insights for Transactions",M+"/us/en/business/cybersecurity-fraud-prevention/identity/insights/identity-insights-for-transactions.html"]]}),
    P("passkeys","Payment Passkeys","Device biometrics replace one-time passcodes at checkout; expanded to Asia Pacific in late 2024.",{s:["con","iss","mer"],lc:"checkout",st:"new",ay:"2024",src:[["Payment Passkeys",M+"/us/en/personal/ways-to-pay/payment-passkeys.html"]]}),
    P("c2p","Click to Pay (EMV Secure Remote Commerce)","Network-recognised guest checkout without typing card details; 26 European markets, enrolments doubled year-on-year in 2025.",{s:["mer","con","iss"],lc:"checkout",note:"Co-developed with the other networks at EMVCo.",src:[["Click to Pay",M+"/us/en/business/payments/commercial-payments/accept-payments/click-to-pay.html"]]}),
    P("biocheckout","Biometric Checkout Program","In-store pay-by-face or palm with identity partners such as NEC.",{s:["mer","con"],lc:"checkout",src:[["NEC press release, 2023","https://www.nec.com/en/press/202311/global_20231114_01.html"]]}),
    P("taponphone","Tap on Phone & Cloud Commerce","A smartphone becomes a contactless terminal; Cloud Commerce hosts ~90% of the tap-to-pay logic in the cloud.",{s:["mer","acq"],lc:"checkout",src:[["Tap on Phone",M+"/us/en/business/payments/commercial-payments/accept-payments/mobile-point-of-sale/tap-on-phone.html"],["Cloud Commerce",M+"/us/en/business/payments/commercial-payments/accept-payments/mobile-point-of-sale/cloud-commerce.html"]]}),
    P("qr","Mastercard QR & Merchant Presented QR","Consumer-initiated QR or alias payments, and merchant-presented QR acceptance at the point of sale.",{s:["mer","acq","con","fin"],lc:"checkout",src:[["Mastercard QR — Developers",D+"/product/mastercard-qr"],["Merchant Presented QR: SRC — Developers",D+"/product/mastercard-merchant-presented-qr-src"]]}),
    P("masterpass","Masterpass","Mastercard's first digital wallet; discontinued in 2019 in favour of Click to Pay and MDES.",{s:["con","mer"],lc:"checkout",st:"retired",src:[["Masterpass — Wikipedia","https://en.wikipedia.org/wiki/Masterpass"]]}),
   ]},
   {id:"3.3", name:"Risk decisioning", blurb:"Decide in milliseconds.", div:"svc", rev:"sec", products:[
    P("dmp","Decision Management Platform (DMP)","The decisioning platform — rules, case management and BI — that powers 20+ Mastercard products, evaluating thousands of rules in tens of milliseconds. Built on Brighterion AI.",{s:["iss","acq","mer"],lc:"auth",o:"A",ay:"2017",at:"Brighterion (engine)",rel:["brighterion","di","dipro","odd"],src:[["Brighterion technology","https://b2b.mastercard.com/ai-and-security-solutions/brighterion-ai/technology/"],["AI-powered decision management (blog)","https://b2b.mastercard.com/news-and-insights/blog/ai-powered-decision-management-key-for-global-credit-card-security/"]]}),
    P("di","Decision Intelligence (DI)","Real-time AI risk score on every transaction for issuers at authorisation.",{s:["iss"],lc:"auth",rel:["dmp"],src:[["Decision Intelligence",M+"/us/en/business/cybersecurity-fraud-prevention/risk-decisioning/decision-intelligence.html"]]}),
    P("dipro","Decision Intelligence Pro","Generative and graph-AI evolution (the MUCI algorithm) that scores transactions from any network; up to 300% uplift in detecting compromised cards.",{s:["iss"],lc:"auth",st:"new",ay:"Feb 2024",src:[["Press release, Feb 2024",M+"/us/en/news-and-trends/press/2024/february/mastercard-supercharges-consumer-protection-with-gen-ai.html"]]}),
    P("odd","On-Demand Decisioning","Issuers set their own authorisation rules directly on the network and choose auto-response or referral.",{s:["iss"],lc:"auth",st:"new",ay:"Oct 2025",src:[["Press release, Sep 2025",M+"/us/en/news-and-trends/press/2025/september/mastercard-customizable-decisioning-solution-for-financial-institutions.html"]]}),
    P("tfm","Transaction Fraud Monitoring (TFM) & A2A TFM","Pre-authorisation risk scores for acquirers, PSPs and payment facilitators, with a variant for account-to-account rails.",{s:["acq"],lc:"auth",src:[["Transaction Fraud Monitoring",M+"/global/en/business/cybersecurity-fraud-prevention/risk-decisioning/transaction-fraud-monitoring.html"]]}),
    P("ems","Expert Monitoring Solutions (EMS)","Behaviour-based card-not-present fraud score at authorisation for US-issued cards.",{s:["mer","acq"],lc:"auth",src:[["EMS via Cybersource docs","https://developer.cybersource.com/docs/cybs/en-us/payments/developer/ctv/rest/payments/payments-intro/payments-features-intro/payments-mc-ems.html"]]}),
    P("fma","Fraud Management Applications","Rule Discovery, Fraud Rule Manager and Case Manager: issuer self-service rule building and case handling on top of DI.",{s:["iss"],lc:"auth",src:[["Fraud Management Applications",M+"/global/en/business/cybersecurity-fraud-prevention/risk-decisioning/fraud-management-application.html"]]}),
    P("obrs","On-Behalf Rules Services","Mastercard-managed rule cartridges, tuned quarterly, for issuers without their own fraud-ops teams.",{s:["iss"],lc:"auth",src:[["On-Behalf Rules Services",M+"/us/en/business/cybersecurity-fraud-prevention/risk-decisioning/on-behalf-rules-services.html"]]}),
    P("merchrisk","Merchant Monitoring with AI · Merchant Risk Decisioning","Acquirer-side merchant risk products listed under Risk Decisioning.",{s:["acq"],src:[["Cybersecurity & fraud prevention hub",M+"/us/en/business/cybersecurity-fraud-prevention.html"]]}),
    P("matchpro","MATCH Pro","The Member Alert To Control High-risk merchants list, as an API: acquirers check a prospective merchant's history before signing an agreement.",{s:["acq"],lc:"before",src:[["MATCH Pro — Developers",D+"/product/match"]]}),
    P("orc","Onboard Risk Check","Merchant-onboarding risk assessment combining Mastercard data and third-party signals so acquirers and payfacs can decide who to board.",{s:["acq","fin"],lc:"before",src:[["Onboard Risk Check — Developers",D+"/product/onboard-risk-check"]]}),
    P("fld","Fraud and Loss Database (SAFE)","System of record for confirmed fraud filed by issuers; consumed by acquirers, the MATCH list and risk models.",{s:["iss","acq"],lc:"after",src:[["FLD — Developers",D+"/product/fld-fraud-submission/"]]}),
    P("medi","Mastercard Early Detect Insights (MEDI)","Authorisation anomaly and false-decline monitoring; the closest match to 'Alert Insights'.",{s:["iss","acq"],lc:"auth",rev:"ins",src:[["MEDI",M+"/us/en/business/insights-intelligence/operations-intelligence/solutions/mastercard-early-detect-insights.html"]]}),
    P("safetynet","Safety Net","Network-level fraud backstop (~2014) that blocks anomalous authorisation patterns even when an issuer has set no limits. No current public page found; may have been absorbed into On-Behalf Rules or DI.",{s:["iss"],lc:"auth",st:"unconf",div:"core"}),
   ]},
   {id:"3.4", name:"Disputes & resolution", blurb:"Fix what goes wrong, before it becomes a chargeback.", div:"svc", rev:"sec", products:[
    P("ethocaalerts","Ethoca Alerts","Near-real-time issuer↔merchant alerts so merchants can refund before a chargeback is filed; 39m chargebacks prevented in 2025.",{s:["mer","iss"],lc:"after",o:"A",ay:"2019",at:"Ethoca",src:[["Ethoca Alerts",M+"/us/en/business/cybersecurity-fraud-prevention/dispute-management/ethoca-alerts.html"]]}),
    P("ethocacc","Ethoca Consumer Clarity","Merchant purchase details and logos surfaced in banking apps and call centres to stop 'I don't recognise this' disputes.",{s:["iss","mer","con"],lc:"after",o:"A",ay:"2019",at:"Ethoca",src:[["Ethoca Consumer Clarity",M+"/global/en/business/cybersecurity-fraud-prevention/dispute-management/ethoca-consumer-clarity.html"]]}),
    P("ethocaelim","Ethoca Eliminator","Automated chargeback elimination on the Alerts network; thinly documented on Mastercard's own site.",{s:["mer"],lc:"after",st:"unconf",o:"A",ay:"2019",at:"Ethoca",src:[["Third-party explainer","https://corepay.net/articles/how-ethoca-eliminator-reduces-chargeback-and-prevents-fraud/"]]}),
    P("mastercom","Mastercom & Dispute Resolution","Core case-management system and the formal chargeback, pre-arbitration and arbitration framework.",{s:["iss","acq","mer"],lc:"after",src:[["Mastercom summary (PDF)",M+"/content/dam/public/mastercardcom/globalrisk/pdf/MastercomDisputeResolutionClaimsManagerExternalSummaryGLOBALJan20.pdf"]]}),
    P("fpt","First-Party Trust & Trusted Transactions","Merchant-shared trust and behavioural signals to fight friendly fraud; expanded to new markets in June 2025.",{s:["mer","iss"],lc:"after",st:"new",src:[["First-Party Trust expansion, Jun 2025",M+"/us/en/news-and-trends/press/2025/june/first-party-trust-countering-friendly-fraud.html"]]}),
    P("merchantid","Merchant Identifier","Resolves unrecognisable merchant names on statements to real merchant details — the classic cause of 'I don't recognise this charge' disputes.",{s:["iss","fin"],lc:"after",src:[["Merchant Identifier — Developers",D+"/product/merchant-identifier"]]}),
   ]},
   {id:"3.5", name:"Account services", blurb:"Keep the credential current; share what happens on it.", div:"core", rev:"dig", products:[
    P("abu","Automatic Billing Updater (ABU)","Pushes reissued card details to enrolled card-on-file merchants so recurring billing doesn't fail.",{s:["mer","iss","con"],lc:"after",src:[["ABU — Developers",D+"/product/automatic-billing-updater-abu/"]]}),
    P("asi","Account Status Inquiry & Payment Account Management","Card-validity checks and account-management APIs, documented mostly through processors' docs.",{s:["mer","acq"],lc:"before",src:[["Payment Account Management — Developers",D+"/product/payment-account-management"]]}),
    P("cardlc","Card lifecycle (Processing Core APIs)","Issuance, reissue, status changes and closure inside Mastercard Processing.",{s:["iss","fin"],lc:"before",rel:["processing"],src:[["Card lifecycle use case",D+"/mastercard-processing-core/documentation/use-cases/card-lifecycle/"]]}),
    P("minna","Minna Technologies","In-app subscription visibility, management and cancellation for banks' customers.",{s:["iss","con"],lc:"after",o:"A",ay:"Oct 2024",at:"Minna Technologies",rev:"eng",src:[["CNBC on the deal","https://www.cnbc.com/2024/10/01/mastercard-to-buy-subscription-management-startup-minna-technologies.html"]]}),
    P("alm","Account Level Management (ALM)","Named in the brief; no current Mastercard product found under this name (Marqeta uses it for its own tooling).",{s:["iss"],st:"unconf"}),
    P("txnnotif","Transaction Notifications","Real-time purchase alerts a cardholder can share with third-party apps and services, with consent managed through Mastercard's Consent Management & Enrollment APIs.",{s:["fin","iss","con"],lc:"after",src:[["Transaction Notifications — Developers",D+"/product/transaction-notifications"]]}),
    P("asc","Account Services Catalogue","One universal specification for account-range and PAN services — enablement, closure, replacement, product graduation and One Credential registration — routed to the right Mastercard service provider.",{s:["iss","fin"],lc:"before",src:[["Account Services Catalogue — Developers",D+"/product/account-services-catalogue"]]}),
    P("acctval","Mastercard Account Validation","Checks a cardholder's name against the issuer's records in real time, for account opening and transaction protection.",{s:["mer","fin","iss"],lc:"before",src:[["Account Validation — Developers",D+"/product/mastercard-account-validation"]]}),
   ]},
   {id:"3.6", name:"Agentic commerce", blurb:"Let an AI agent pay — safely.", div:"core", rev:"dig", products:[
    P("agentpay","Mastercard Agent Pay","Framework for AI agents to transact on a person's or business's behalf: trusted agent registration, safe transactions, consumer control and fraud protection. Partners include Microsoft, IBM, PayPal, Google, Braintree and Checkout.com.",{s:["ai","mer","iss","con"],lc:"checkout",st:"new",ay:"Apr 2025",rel:["agentictokens","kya","vintent","ap4m","agentsuite"],src:[["Agent Pay unveiled, Apr 2025",M+"/global/en/news-and-trends/press/2025/april/mastercard-unveils-agent-pay-pioneering-agentic-payments-technology-to-power-commerce-in-the-age-of-ai.html"],["Agent Pay product page",M+"/global/en/business/artificial-intelligence/mastercard-agent-pay.html"]]}),
    P("agentictokens","Agentic Tokens","MDES-derived tokens that carry which agent is acting and on whose behalf, end to end.",{s:["ai","iss","mer"],lc:"checkout",st:"new",ay:"2025",rel:["mdes"],src:[["Agentic commerce momentum",M+"/global/en/news-and-trends/stories/2025/agentic-commerce-momentum.html"]]}),
    P("kya","Know Your Agent (KYA)","Registration and verification so only vetted, traceable agents can obtain agentic tokens — 'KYC for AI agents'.",{s:["ai","iss"],lc:"before",st:"new",ay:"2025",src:[["Checkout.com interview","https://www.checkout.com/blog/mastercard-checkout-discuss-agentic-commerce-agent-pay"]]}),
    P("vintent","Verifiable Intent","Open, standards-based proof that an agent acted within explicit consumer authorisation; co-developed with Google (AP2/UCP-aligned). Interoperability talks with Visa's Trusted Agent Protocol, September 2026.",{s:["ai","mer","iss","con"],lc:"checkout",st:"new",ay:"Mar 2026",src:[["Verifiable Intent",M+"/global/en/news-and-trends/stories/2026/verifiable-intent.html"],["Finextra: Verifiable Intent vs Visa TAP","https://www.finextra.com/blogposting/31107/deep-dive-mastercard-verifiable-intent-vs-visa-trusted-agent-protocol"]]}),
    P("ap4m","Agent Pay for Machines (AP4M)","Machine-to-machine, high-frequency, low-value payments across cards, accounts and stablecoins; 30+ launch partners including Stripe, Adyen, Coinbase and the Solana Foundation.",{s:["ai","corp"],lc:"checkout",st:"new",ay:"Jun 2026",src:[["Launch press release, Jun 2026",M+"/global/en/news-and-trends/press/2026/june/mastercard-launches-agent-pay-for-machines.html"]]}),
    P("agentsign","'Agent Sign' / 'Verified Agents'","Not found as official names; the functional equivalents are Know Your Agent and Verifiable Intent.",{s:["ai"],st:"unconf",rel:["kya","vintent"]}),
   ]},
  ]},

 {id:"L2", name:"Rails", analogy:"drivers · I/O", color:"--l2",
  desc:"Mastercard is multi-rail: six ways money and account data move, all plugging into the same kernel and able to call the same network services. Cards earn Payment network revenue; the other rails report inside Value-added services.",
  tiles:[
   {id:"2.1", name:"Card rails", blurb:"Credit, debit, prepaid, commercial.", div:"core", rev:"net", products:[
    P("cardsconsumer","Credit, debit & prepaid card products","Consumer card programmes on the core network — the source of the Payment network revenue line.",{s:["iss","con"],lc:"auth",src:[["Consumer payments",M+"/us/en/business/payments/consumer-payments.html"]]}),
    P("cardscommercial","Commercial card products","SME, T&E, purchasing, virtual and fleet programmes. Fleet cards (bp, Fuelman, Comdata) are partner co-brands riding the network.",{s:["iss","corp"],lc:"auth",div:"cnpf",src:[["Commercial payments",M+"/us/en/business/payments/commercial-payments.html"]]}),
    P("installments","Mastercard Installments","BNPL built into existing cards so issuers can offer instalment plans without a separate loan product; LoanPro partnership 2025.",{s:["iss","mer","con"],lc:"checkout",ay:"2021",note:"Vyze (acquired 2019) underpinned the instalments capability.",src:[["Mastercard Installments",M+"/global/en/business/payments/consumer-payments/next-gen-payments/mastercard-installments.html"]]}),
    P("contactless","Contactless, EMV & open-loop transit","Tap-to-pay at POS and tap-to-ride on transit (Transport NSW; Azerbaijan, November 2025).",{s:["acq","mer","gov","con"],lc:"checkout",src:[["Open-loop transit, Azerbaijan 2025",M+"/news/eemea/en/newsroom/press-releases/en/2025-1/november/mastercard-accelerates-the-future-of-mobility-with-open-loop-transit-payments-in-azerbaijan/"]]}),
   ]},
   {id:"2.2", name:"A2A & real-time", blurb:"Bank-account rails, mostly Vocalink.", div:"core", rev:"oth", products:[
    P("vocalink","Vocalink","Operator and technology provider of national real-time and bulk payment infrastructures.",{s:["iss","gov"],lc:"settle",st:"flux",o:"A",ay:"2016",at:"Vocalink (~£700m; full ownership later)",note:"Mastercard was reported in 2025–26 to be exploring the sale of a 51% stake to a UK bank consortium, after a £11.9m Bank of England fine in July 2025.",src:[["Vocalink acquisition, 2016",I+"/investor-news/investor-news-details/2016/MasterCard-Announces-Acquisition-of-VocaLink/default.aspx"],["The Paypers on the stake sale","https://thepaypers.com/mergers-aquisitions-and-investments/news/mastercard-examines-sale-of-uk-payments-subsidiary-vocalink"],["Bank of England final notice, Jul 2025","https://www.bankofengland.co.uk/-/media/boe/files/prudential-regulation/regulatory-action/2025/final-notice-from-boe-and-pra-to-vocalink.pdf"]]}),
    P("fps","UK Faster Payments infrastructure","Vocalink runs the real-time rail behind the UK's Faster Payment System.",{s:["iss","con"],lc:"settle",st:"flux",o:"A",ay:"2016",at:"Vocalink",src:[["Vocalink — about","https://www.vocalink.com/about/"]]}),
    P("bacs","UK Bacs","Bulk direct debit and direct credit: 4.4bn+ automated payments a year (~90% of salaries, ~98% of state benefits).",{s:["iss","corp","gov"],lc:"settle",st:"flux",o:"A",ay:"2016",at:"Vocalink",src:[["Bacs case study",M+"/us/en/news-and-trends/Insights/2025/over-4-4-billion-automated-payments-annually.html"]]}),
    P("pbba","Pay by Bank app (UK)","Account-to-account merchant payment scheme run by Vocalink.",{s:["mer","con","iss"],lc:"checkout",o:"A",ay:"2016",at:"Vocalink",src:[["Newsroom, 2018",M+"/news/europe/en-uk/newsroom/press-releases/en-gb/2018/january/vocalink-s-pay-by-bank-app-to-partner-with-shieldpay-to-provide-secure-yet-seamless-transactions/"]]}),
    P("a2astack","Instant Payment Service · Bulk Payment Service · Proxy Directory Service · Pay by Account","The productised account-to-account stack Mastercard markets to banks and central infrastructures.",{s:["iss","gov"],lc:"settle",src:[["b2b.mastercard.com","https://b2b.mastercard.com/"]]}),
    P("a2acommerce","Account to Account Commerce","Lets creditor and debtor service providers offer mobile account-to-account payment journeys — payments, refunds, agreements and reconciliation over MTLS APIs.",{s:["iss","fin","mer"],lc:"checkout",src:[["Account to Account Commerce — Developers",D+"/product/account-to-account-commerce"]]}),
    P("betalingsservice","Betalingsservice (Denmark)","Denmark's automatic bill-payment scheme, run by Mastercard Payment Services since the Nets acquisition; the BS Creditor API manages delegated mandates.",{s:["corp","iss","con"],lc:"settle",o:"A",ay:"2019 (closed 2021)",at:"Nets A2A",src:[["BS Creditor API — Developers",D+"/product/bs-creditor-api"]]}),
    P("nets","Nets account-to-account business","Nordic real-time and bulk clearing infrastructure.",{s:["iss"],lc:"settle",o:"A",ay:"2019 (closed 2021)",at:"Nets A2A",src:[["Completion, 2021",I+"/investor-news/investor-news-details/2021/Mastercard-Completes-Acquisition-of-Nets-Account-to-Account-Payment-Business/default.aspx"]]}),
    P("rtpbuilds","National real-time payment builds","Vocalink technology behind The Clearing House RTP (US), Canada's Real-Time Rail (launch targeted Q4 2026), Saudi Arabia's sarie and Peru's CCE (Peru's current status unclear).",{s:["gov","iss"],lc:"settle",o:"A",ay:"2016",at:"Vocalink",src:[["The Clearing House RTP","https://www.theclearinghouse.org/payment-systems/articles/2017/11/20171114-rtp-first-new-core-payments-system"],["Payments Canada — RTR","https://www.payments.ca/systems-services/payment-systems/real-time-rail-payment-system"]]}),
    P("p27","P27 Nordic Payments Platform","Pan-Nordic clearing platform Vocalink was selected to build in 2019; collapsed in 2023 after Danish banks withdrew.",{s:["iss"],lc:"settle",st:"retired",src:[["P27 post-mortem","https://flagshipadvisorypartners.com/insights/p27-lessons-learned-from-the-latest-failure-in-pan-european-payment-collaborations/"]]}),
   ]},
   {id:"2.3", name:"Mastercard Move", blurb:"Push payments and cross-border.", div:"cnpf", rev:"oth", products:[
    P("move","Mastercard Move","Umbrella brand for money movement: 200+ countries, 150+ currencies, ~17bn endpoints across cards, accounts, wallets and cash.",{s:["iss","fin","corp","gov"],lc:"settle",ay:"2023 (brand)",src:[["Mastercard Move",M+"/us/en/business/payments/mastercard-move.html"]]}),
    P("send","Mastercard Send","Real-time push-to-card API for disbursements, P2P, gig payouts and insurance claims.",{s:["iss","fin","corp"],lc:"settle",ay:"~2017 (ex-MoneySend)",src:[["Mastercard Send — Developers",D+"/product/mastercard-send/"]]}),
    P("xborder","Cross-Border Services","Multi-rail cross-border network paying out to bank accounts, wallets, cards and 300,000+ cash locations.",{s:["iss","fin","corp"],lc:"settle",o:"A",ay:"2019",at:"Transfast (+ HomeSend JV)",src:[["Transfast acquisition, 2019",I+"/investor-news/investor-news-details/2019/Mastercard-Advances-Cross-Border-Capabilities-with-Acquisition-of-Transfast/default.aspx"]]}),
    P("movecomm","Move Commercial Payments","Bank-to-bank cross-border B2B payments with upfront FX transparency; positioned against Visa B2B Connect.",{s:["iss","corp"],lc:"settle",st:"new",ay:"Oct 2024",src:[["Press release, Oct 2024",M+"/us/en/news-and-trends/press/2024/october/mastercard-transforms-cross-border-payments-for-banks-with-industry-first-innovation.html"]]}),
    P("disb","Disbursements & remittances partnerships","Government benefits, payroll, insurance and remittances through partners such as Félix, Remitly, MoneyGram, Corpay and VoPay.",{s:["gov","corp","fin","con"],lc:"settle",src:[["Corpay partnership, 2025","https://s25.q4cdn.com/479285134/files/doc_news/Mastercard-and-Corpay-Launch-Strategic-Partnership-in-Cross-Border-Payments-2025.pdf"]]}),
    P("tips","TIPS cross-currency pilot","Pilot connecting Move rails to the Eurosystem's TARGET Instant Payment Settlement for instant cross-currency settlement.",{s:["iss"],lc:"settle",st:"new",ay:"Jun 2026",src:[["Press release, Jun 2026",M+"/us/en/news-and-trends/press/2026/june/Mastercard-advances-instant-cross-border-payments-with-TIPS-cross-currency-pilot.html"]]}),
   ]},
   {id:"2.4", name:"Digital assets", blurb:"Tokenised money, stablecoins, crypto.", div:"core", rev:"oth", products:[
    P("mtn","Multi-Token Network (MTN)","Blockchain platform for tokenised deposits and regulated money with 24/7 interbank settlement; interoperates with J.P. Morgan Kinexys; Ondo Finance joined in 2025.",{s:["iss","fin"],lc:"settle",ay:"2023",src:[["Multi-Token Network",M+"/us/en/business/payments/consumer-payments/next-gen-payments/digital-asset-solutions/multi-token-network.html"]]}),
    P("stable","Stablecoin settlement","Network-wide option to settle in regulated stablecoins (USDC, PYUSD, USDG, USDP, RLUSD, SoFiUSD) across chains including Ethereum, Solana, Base, Polygon and XRPL, with intraday and weekend windows.",{s:["iss","acq"],lc:"settle",st:"new",ay:"expanded Jun 2026",src:[["Press release, Jun 2026",M+"/global/en/news-and-trends/press/2026/june/mastercard-expands-settlement-capabilities-to-include-stablecoin.html"]]}),
    P("bvnk","BVNK","Stablecoin-powered financial stack for enterprises across 130+ countries — the bridge between on-chain payments and fiat rails.",{s:["corp","fin"],lc:"settle",st:"new",o:"A",ay:"Mar 2026 (closed Aug 2026)",at:"BVNK (up to $1.8bn incl. $300m contingent)",src:[["Acquisition announcement, Mar 2026",M+"/us/en/news-and-trends/press/2026/march/Mastercard-to-acquire-BVNK-to-connect-on-chain-payments-and-fiat-rails.html"]]}),
    P("cryptocred","Mastercard Crypto Credential","Username-based crypto transfers with VASP verification, chain and asset compatibility checks and Travel Rule support; partners include Bit2me, Bybit, Mercado Bitcoin and Mercuryo.",{s:["fin","con"],lc:"checkout",ay:"2024",src:[["First P2P pilot, May 2024",M+"/us/en/news-and-trends/press/2024/may/mastercard-crypto-credential-goes-live-with-first-peer-to-peer-pilot-transactions-adds-new-partners-to-the-ecosystem.html"]]}),
    P("cryptocards","Crypto card programmes","Mastercard-branded cards issued by exchanges such as Binance and Bybit — a programme category rather than a single product.",{s:["fin","con"],lc:"checkout",note:"Partner co-brand issuance on the core network."}),
   ]},
   {id:"2.5", name:"Bill pay & local", blurb:"Billers, local wallets.", div:"cnpf", rev:"oth", products:[
    P("billpay","Mastercard Bill Pay","Biller connectivity for recurring and one-off bill payments through banking apps; strengthened by Transactis (2019). The 2018-era 'Bill Pay Exchange' brand no longer appears on the site.",{s:["iss","corp","con"],lc:"checkout",st:"unconf",note:"Transactis acquired 2019 for bill-pay and e-invoicing technology.",src:[["Transactis acquisition, 2019","https://www.businesswire.com/news/home/20190503005240/en/Mastercard-Strengthens-Bill-Payment-Services-Acquisition-Transactis"],["Bill Pay — Developers",D+"/product/bill-pay"]]}),
    P("arcus","Arcus","Latin-American (Mexico) real-time bill-pay and disbursement infrastructure; no 2025–26 news found.",{s:["corp","iss","con"],lc:"checkout",st:"unconf",o:"A",ay:"2021",at:"Arcus",src:[["Acquisition, 2021",M+"/news/latin-america/en/newsroom/press-releases/pr-en/2021/november/mastercard-expands-support-of-latin-america-real-time-payments-with-acquisition-of-arcus/"]]}),
    P("rpps","RPPS (Remote Payment and Presentment Service)","Mastercard's US electronic bill-payment network connecting banks and billers; the Bill Payment Validator API checks whether an account can be paid through it.",{s:["iss","corp","fin"],lc:"settle",src:[["Bill Payment Validator — Developers",D+"/product/bill-payment-validator"]]}),
    P("paylocal","Mastercard Pay Local","Lets cardholders pay through local wallets (Alipay, GrabPay, M-Pesa, Mercado Pago, DANA, Touch 'n Go) where cards aren't accepted.",{s:["fin","mer","con"],lc:"checkout",st:"new",ay:"Nov 2024",div:"core",src:[["Launch, Nov 2024",M+"/global/en/news-and-trends/press/2024/november/mastercard-launches-pay-local-to-empower-digital-wallet-providers-with-new-ways-to-pay.html"]]}),
   ]},
   {id:"2.6", name:"Open Finance", blurb:"Bank-account data and account-to-account initiation, with consent.", div:"svc", rev:"oth", products:[
    P("ofus","Mastercard Open Finance US (Finicity)","Account and owner verification, Payment Success Indicator, Deposit Switch, Bill Pay Switch, data enrichment, Consumer Foresight, lending and mortgage verification, small-business cash-flow analytics; ~95% of US deposit accounts.",{s:["iss","fin","mer","corp"],lc:"before",o:"A",ay:"2020",at:"Finicity (~$825m)",src:[["Open Finance (US)",M+"/us/en/business/open-finance.html"],["Open Finance US — developer docs",D+"/open-finance-us/documentation/"]]}),
    P("ofeu","Mastercard Open Finance Europe (Aiia)","SCA-based account connection, data retrieval and payment initiation across Europe; the Aiia brand is converging into Open Finance.",{s:["fin","mer","iss"],lc:"before",st:"flux",o:"A",ay:"2021",at:"Aiia",src:[["Aiia Enterprise docs",D+"/open-finance-europe/documentation/licensed/aiia-enterprise/"]]}),
    P("dataconnect","Mastercard Data Connect","Consumer-permissioned data-sharing and consent layer across the US and European stacks.",{s:["iss","fin","con"],lc:"before",ay:"2024",src:[["Mastercard Data Connect",M+"/us/en/business/open-finance/solutions/data/mastercard-data-connect.html"]]}),
    P("fdxhub","Developer Hub for FDX APIs","Tooling for banks and data providers to publish FDX-compliant open-banking APIs (the US Financial Data Exchange standard).",{s:["iss","fin"],lc:"before",src:[["FDX Developer Hub — Developers",D+"/product/fdx-developer-hub"]]}),
    P("paybybankus","Pay by Bank (US)","Account-to-account payment initiation delivered through the Open Finance stack rather than as a standalone rail.",{s:["mer","con","iss"],lc:"checkout",note:"US regulatory context: CFPB Section 1033 was enjoined and under reconsideration in 2026; no sign of Mastercard winding down Finicity or Aiia.",src:[["Open Finance (US)",M+"/us/en/business/open-finance.html"]]}),
   ]},
  ]},

 {id:"L1", name:"Kernel", analogy:"the network itself", color:"--l1",
  desc:"The thing everything else runs on: the switch, the brands, the rules and the data the network throws off. This is where the Payment network revenue line (~69% of FY2025) is earned.",
  tiles:[
   {id:"1.1", name:"The switch", blurb:"Authorise, clear, settle.", div:"core", rev:"net", products:[
    P("swcore","Global switching network","Authorisation, clearing and settlement between issuers and acquirers in 210+ countries and territories and 150+ currencies.",{s:["iss","acq"],lc:"auth",ay:"1966",src:[["Mastercard — Wikipedia","https://en.wikipedia.org/wiki/Mastercard"]]}),
    P("standin","Stand-In Authorization","Mastercard authorises on the issuer's behalf when the issuer's host is unavailable ('payment resiliency').",{s:["iss"],lc:"auth",src:[["Payment resiliency",M+"/global/en/business/cybersecurity-fraud-prevention/cybersecurity/on-demand-decisioning.html"]]}),
    P("cbfm","Cross Border Fee Manager","Issuer tooling for cross-border fee logic; grouped by Mastercard under payment resiliency.",{s:["iss"],lc:"auth",src:[["Cybersecurity & fraud prevention hub",M+"/us/en/business/cybersecurity-fraud-prevention.html"]]}),
    P("fx","Currency Conversion Calculator","Mastercard's foreign-exchange rates and settlement-currency conversion, retrievable instantly by API.",{s:["iss","acq","fin"],lc:"settle",src:[["Currency Conversion Calculator — Developers",D+"/product/currency-conversion-calculator"]]}),
    P("directservices","Mastercard Direct Services","Lets customers call Mastercard's value-added services on every transaction — including non-switched, on-us and non-Mastercard-branded ones.",{s:["iss","acq","fin"],lc:"auth",src:[["Direct Services — Developers",D+"/product/direct-service-api"]]}),
   ]},
   {id:"1.2", name:"Brands & credentials", blurb:"What's on the card.", div:"core", rev:"net", products:[
    P("brandmc","Mastercard","The consumer and commercial card brand: credit, debit, prepaid and commercial products in tiers from Standard to World Legend.",{s:["iss","con","corp"],lc:"before",ay:"1966",src:[["Card benefits",M+"/us/en/personal/find-a-card/card-benefits.html"]]}),
    P("maestro","Maestro","International PIN-debit brand, used mainly outside the US.",{s:["iss","con"],lc:"before",ay:"1992",src:[["Maestro — Wikipedia","https://en.wikipedia.org/wiki/Maestro_(debit_card)"]]}),
    P("cirrus","Cirrus","Global ATM and cash-access network brand.",{s:["iss","con"],lc:"before",o:"A",ay:"1988",at:"Cirrus",src:[["Cirrus — Wikipedia","https://en.wikipedia.org/wiki/Cirrus_(interbank_network)"]]}),
   ]},
   {id:"1.3", name:"Franchise & rules", blurb:"The contract everyone signs.", div:"core", rev:"net", products:[
    P("rules","Mastercard Rules & compliance programmes","Scheme rules, licensing, interchange, BIN ranges, MATCH, the Scam Merchant Monitoring Program and dispute rules.",{s:["iss","acq"],src:[["Rules and compliance programs",M+"/us/en/business.html"]]}),
    P("nep","Network Enablement Partners & payment-facilitator directory","Accredited third parties that help customers connect to and operate on the network.",{s:["acq","fin"],lc:"before",src:[["Mastercard for business",M+"/us/en/business.html"]]}),
    P("binlookup","BIN Lookup","Up-to-date active Mastercard issuing account ranges for authorisation routing, fraud prevention and loyalty checks; single lookup, filtering and full or incremental download.",{s:["acq","mer","fin","iss"],lc:"auth",src:[["BIN Lookup — Developers",D+"/product/bin-lookup"]]}),
   ]},
   {id:"1.4", name:"Data & AI foundation", blurb:"What the network throws off.", div:"svc", rev:"na", products:[
    P("data","Network data asset","Anonymised transaction data from the network: the raw material for every intelligence product in the Network services and Solutions layers.",{s:["iss","acq","mer","corp","gov"],lc:"after",div:"core"}),
    P("dataai","Data & AI organisation","Cross-company org created in the May 2024 reorg under Chief AI & Data Officer Greg Ulrich, for AI and data commercialisation and governance.",{s:["iss","mer","corp"],ay:"2024",src:[["Reorg press release, Apr 2024",M+"/us/en/news-and-trends/press/2024/april/positioning-mastercard-for-the-next-era-of-growth.html"]]}),
    P("brighterion","Brighterion AI","AI decisioning engine with 20+ years of history; the technology core of the Decision Management Platform.",{s:["iss","acq","mer"],lc:"auth",o:"A",ay:"2017",at:"Brighterion",rev:"sec",rel:["dmp"],src:[["Brighterion technology","https://b2b.mastercard.com/ai-and-security-solutions/brighterion-ai/technology/"]]}),
   ]},
  ]},
];

const PILLARS = [
 {id:"pillar-brand", name:"Brand & Priceless", color:"--lu", blurb:"The consumer-facing brand and its experience platform.", products:[
   P("brand","Mastercard brand & sponsorships","The Priceless platform and global sponsorships across sport, music and culture.",{s:["con","iss"],div:"corp",rel:["priceless"],src:[["Priceless","https://www.priceless.com/about"]]}),
   P("sonic","Sonic Branding","The six-note sonic signature and animation played at checkout as a multisensory confirmation; available to partners as an SDK.",{s:["mer","acq","fin"],div:"corp",lc:"checkout",src:[["Sonic Branding — Developers",D+"/product/mastercard-sonic-branding"]]}),
 ]},
 {id:"pillar-inclusion", name:"Inclusive growth", color:"--lu", blurb:"Impact programmes that widen who the network serves.", products:[
   P("cig","Center for Inclusive Growth","Mastercard's philanthropic arm (2014): financial health, small-business growth, tech for good; hosts the annual Global Inclusive Growth Forum.",{s:["gov","corp"],div:"corp",ay:"2014",src:[["mastercardcenter.org","https://www.mastercardcenter.org/"]]}),
   P("communitypass","Community Pass & Farm Pass","Shared digital-ID and payments infrastructure for rural and underserved communities; the MADE Alliance: Africa targets 100m people and businesses by 2034.",{s:["gov","con","corp"],div:"corp",src:[["Community Pass",M+"/europe/en/for-the-world/prosperity/community-pass.html"]]}),
   P("strive","Mastercard Strive","Small-business programme: 1.5m+ reached and $150m+ credit facilitated in India as of September 2026.",{s:["corp","gov"],div:"corp",src:[["Strive India milestone, Sep 2026",M+"/news/ap/en-in/newsroom/press-releases/en-in/2026/september-1/mastercard-strive-in-india-reaches-over-1-5-million-and-individuals-supporting-their-journey-to-financial-health/"]]}),
   P("donate","Mastercard Donate","Lets partners embed charitable giving in their websites and apps — round-ups and one-off donations to vetted causes.",{s:["mer","iss","fin","con"],div:"corp",lc:"after",src:[["Mastercard Donate — Developers",D+"/product/mastercard-donate"]]}),
 ]},
 {id:"pillar-trust", name:"Trust & regulation", color:"--lu", blurb:"The licence to operate.", products:[
   P("regulation","Regulatory positioning","CFPB Section 1033 (US open banking) enjoined and under reconsideration in 2026; UK scrutiny of Vocalink ownership; the 2026 leadership reshuffle unified go-to-market under a Chief Business Officer.",{s:["iss","gov"],div:"corp",rel:["vocalink","ofus","rules","trustcenter"],src:[["Leadership updates, Jun 2026",M+"/us/en/news-and-trends/press/2026/june/mastercard-leadership-updates.html"]]}),
 ]},
];

