/* =========================================================
   JOURNEYS — the flows that matter most, by scale and by novelty.
   Each step lands on one tile (or user chip); p = the product it opens.
   ========================================================= */
const JGROUPS = [
 {id:"scale", name:"Everyday, at scale", d:"The flows that carry most of the volume"},
 {id:"money", name:"Money movement & commercial", d:"Beyond the consumer purchase"},
 {id:"trust", name:"Trust & resilience", d:"What happens when something goes wrong"},
 {id:"frontier", name:"Frontier", d:"New in 2025–26"},
];
const JOURNEYS = [
 {id:"tap", g:"scale", name:"Tap to pay in store", why:"The single largest flow on the network. A card or phone tap runs the whole stack in under a second.",
  scale:"~75% of in-person transactions were contactless by Q3 2024; 210bn switched purchase transactions and ~150m acceptance locations in 2025.", src:[["Investor Day 2024 (PDF)","https://s25.q4cdn.com/479285134/files/doc_events/2024-Mastercard-Investment-Community-Presentation.pdf"],["4Q25 earnings release (PDF)","https://s25.q4cdn.com/479285134/files/doc_financials/2025/q4/4Q25-Mastercard-Earnings-Release.pdf"]],
  steps:[
   {at:"u-con", t:"A shopper taps a card or phone", d:"A physical card, or a wallet token provisioned by MDES."},
   {at:"3.1", p:"mdes", t:"If it's a phone, MDES supplies the token", d:"The merchant never sees the real card number."},
   {at:"3.2", p:"taponphone", t:"The terminal — or a Tap on Phone device — reads it", d:"Cloud Commerce runs most of the contactless kernel in the cloud."},
   {at:"u-acq", t:"The acquirer forwards the authorisation", d:""},
   {at:"2.1", p:"cardsconsumer", t:"It rides the card rail", d:""},
   {at:"1.1", p:"swcore", t:"The switch routes it to the issuer", d:"Milliseconds, in 220+ countries and territories."},
   {at:"3.3", p:"di", t:"Decision Intelligence scores it in flight", d:"The issuer gets a real-time AI risk score with the request."},
   {at:"u-iss", t:"The issuer approves", d:""},
   {at:"3.5", p:"txnnotif", t:"A real-time alert reaches the cardholder's app", d:"Transaction Notifications, with consent."},
   {at:"4.3", p:"spendingpulse", t:"…and the aggregate becomes SpendingPulse", d:"The flywheel turns."},
  ]},
 {id:"ecom", g:"scale", name:"Online checkout", why:"Where tokenisation, authentication and fraud scoring all meet — and where Mastercard has committed to removing manual card entry in Europe by 2030.",
  scale:"~50% of European e-commerce transactions tokenised by mid-2025; Click to Pay enrolments doubled year-on-year; Merchant Cloud connects 240+ acquirers.", src:[["Tokenisation one-year update, Jun 2025","https://www.businesswire.com/news/home/20250603515548/en"],["Merchant Cloud launch, Oct 2025","https://www.mastercard.com/us/en/news-and-trends/press/2025/october/Mastercard-Merchant-Cloud-simplify-and-support-commerce-growth-in-global-acceptance-ecosystem.html"]],
  steps:[
   {at:"u-con", t:"A shopper chooses to pay", d:"Card on file, wallet or guest checkout."},
   {at:"3.2", p:"c2p", t:"Click to Pay + a Payment Passkey", d:"No card number typed; biometrics replace the OTP."},
   {at:"3.1", p:"mdes", t:"MDES swaps the PAN for a token", d:""},
   {at:"5.2", p:"merchantcloud", t:"Merchant Cloud / Gateway carries the request", d:"Routes to the acquirer with fraud and identity signals attached."},
   {at:"2.1", p:"cardsconsumer", t:"Rides the card rail", d:""},
   {at:"1.1", p:"swcore", t:"The switch routes to the issuer", d:""},
   {at:"3.2", p:"idcheck", t:"Identity Check authenticates if the risk warrants it", d:"EMV 3-D Secure, mostly frictionless."},
   {at:"3.3", p:"di", t:"Decision Intelligence scores the risk", d:""},
   {at:"u-iss", t:"The issuer approves", d:""},
   {at:"3.4", p:"ethocaalerts", t:"Afterwards: Ethoca, ABU, Pay Rewards", d:"Disputes headed off, credentials kept current, points redeemed."},
  ]},
 {id:"subs", g:"scale", name:"A subscription renews", why:"Recurring card-on-file payments are the fastest-growing consumer flow, and the one most likely to end in a dispute or a cancelled card.",
  scale:"6.8bn subscriptions globally, heading for 9.3bn by 2028 (Juniper, cited by Mastercard); Ethoca prevented 39m chargebacks in 2025.", src:[["Mastercard on the subscription economy, 2024","https://www.mastercard.com/us/en/news-and-trends/stories/2024/sign-us-up-transforming-the-subscription-experience.html"],["Ethoca Alerts","https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/dispute-management/ethoca-alerts.html"]],
  steps:[
   {at:"u-mer", t:"The merchant bills the stored credential", d:"Monthly, without the customer present."},
   {at:"3.1", p:"scof", t:"Secure Card on File holds a token, not a PAN", d:""},
   {at:"3.5", p:"abu", t:"ABU has already refreshed any reissued card details", d:"So the renewal doesn't fail on an expired card."},
   {at:"2.1", p:"cardsconsumer", t:"Rides the card rail", d:""},
   {at:"1.1", p:"swcore", t:"The switch routes to the issuer", d:""},
   {at:"3.3", p:"di", t:"Decision Intelligence scores it", d:"Recurring patterns are low-risk by design."},
   {at:"u-iss", t:"The issuer approves", d:""},
   {at:"3.4", p:"ethocacc", t:"Consumer Clarity shows the merchant and receipt in the banking app", d:"Fewer 'I don't recognise this' calls."},
   {at:"3.5", p:"minna", t:"Subscription Controls let the cardholder manage or cancel", d:"Minna Technologies, inside the bank's app."},
   {at:"3.4", p:"ethocaalerts", t:"If it's disputed anyway, Ethoca Alerts prompt a refund", d:"Before it becomes a chargeback."},
  ]},
 {id:"travel", g:"scale", name:"Paying abroad", why:"Cross-border spending is Mastercard's most valuable flow per transaction and its fastest-growing consumer volume.",
  scale:"Cross-border volume grew 15% in 2025; the network operates in 220+ countries and territories.", src:[["4Q25 earnings release (PDF)","https://s25.q4cdn.com/479285134/files/doc_financials/2025/q4/4Q25-Mastercard-Earnings-Release.pdf"]],
  steps:[
   {at:"u-con", t:"A traveller pays in a foreign country", d:"Tap, chip, or a local wallet."},
   {at:"2.5", p:"paylocal", t:"Where cards aren't accepted, Pay Local pays through a local wallet", d:"Alipay, GrabPay, M-Pesa, Mercado Pago…"},
   {at:"u-acq", t:"A foreign acquirer forwards the authorisation", d:""},
   {at:"1.1", p:"swcore", t:"The switch routes it cross-border", d:""},
   {at:"1.1", p:"fx", t:"Converted at Mastercard's FX rate", d:"Currency Conversion Calculator exposes the same rates by API."},
   {at:"3.3", p:"di", t:"Decision Intelligence scores an unusual location", d:"Travel patterns, not just a single merchant, inform the score."},
   {at:"u-iss", t:"The home issuer approves and applies cross-border fees", d:"Cross Border Fee Manager logic."},
   {at:"4.2", p:"priceless", t:"Priceless, airport lounges and travel benefits ride along", d:"Card-tier benefits and Travel & Lifestyle Services."},
  ]},
 {id:"billpay", g:"scale", name:"Paying the bills", why:"Not every payment is a card payment. In the UK, the bulk rails Mastercard operates move most salaries, bills and benefits.",
  scale:"Bacs processes 4.4bn+ automated payments a year — ~90% of UK salaries, ~70% of household bills and ~98% of state benefits.", src:[["Bacs case study","https://www.mastercard.com/us/en/news-and-trends/Insights/2025/over-4-4-billion-automated-payments-annually.html"]],
  steps:[
   {at:"u-corp", t:"A biller submits a direct-debit collection", d:"Utilities, mortgages, subscriptions."},
   {at:"2.2", p:"bacs", t:"Bacs collects it in the daily bulk cycle", d:"Three-day cycle; mandates managed by the biller."},
   {at:"2.2", p:"vocalink", t:"Vocalink clears and settles between the banks", d:"The same operator runs Faster Payments."},
   {at:"u-iss", t:"The payer's bank debits the account", d:""},
   {at:"2.5", p:"rpps", t:"In the US, RPPS plays the same role for bill payments", d:"Bill Payment Validator checks the account first."},
   {at:"u-con", t:"The consumer sees the bill paid", d:"Optionally through Bill Pay in the banking app."},
  ]},

 {id:"payout", g:"money", name:"A gig payout in seconds", why:"Push-to-card turned the card rail around: money flows to the cardholder, not from them. Insurers, marketplaces and payroll platforms run on it.",
  scale:"Mastercard Move reaches 10bn+ endpoints and over 95% of the world's banked population, from 60+ originating to 155+ receiving countries.", src:[["Investor Day 2024 (PDF)","https://s25.q4cdn.com/479285134/files/doc_events/2024-Mastercard-Investment-Community-Presentation.pdf"],["Mastercard Move","https://www.mastercard.com/us/en/business/payments/mastercard-move.html"]],
  steps:[
   {at:"u-corp", t:"A platform approves a payout", d:"A driver's earnings, an insurance claim, a refund."},
   {at:"5.1", p:"developers", t:"One call to the Mastercard Send API", d:""},
   {at:"2.3", p:"send", t:"Send pushes the funds to the debit card", d:"An original credit transaction rather than a purchase."},
   {at:"2.3", p:"move", t:"Move routes to a card, account, wallet or cash pick-up", d:"Whichever endpoint the recipient has."},
   {at:"1.1", p:"swcore", t:"The switch carries the credit to the issuer", d:""},
   {at:"u-iss", t:"The issuer posts the credit", d:""},
   {at:"u-con", t:"Money is on the card in seconds", d:""},
  ]},
 {id:"remit", g:"money", name:"A cross-border remittance", why:"Remittances are the most human money flow on the network — and the one most exposed to scams and mule accounts.",
  scale:"Cross-Border Services pays out to bank accounts, wallets, cards and 300,000+ cash locations; A2A Protect cut UK APP fraud by ~20% in 2024.", src:[["Cross-Border Services capabilities (PDF)","https://b2b.mastercard.com/media/u2tbr4d0/mastercard-cross-border-services-capabilities-paper_v2.pdf"],["A2A Protect, 2025","https://www.mastercard.com/news/europe/en-uk/newsroom/press-releases/en-gb/2025/prevent-protect-and-recover-mastercard-strengthens-trust-in-account-to-account-payments/"]],
  steps:[
   {at:"u-fin", t:"A remittance fintech takes an order", d:"Sender wants to pay a family member abroad."},
   {at:"5.1", p:"developers", t:"Calls the Cross-Border Services API", d:"One integration, many corridors."},
   {at:"2.3", p:"xborder", t:"Move Cross-Border Services routes the payment", d:"Bank account, wallet, card or cash pick-up."},
   {at:"4.1", p:"a2aprotect", t:"A2A Protect and TRACE screen for scams and mules", d:"Risk scored on the account-to-account leg."},
   {at:"2.2", p:"a2astack", t:"Lands on a local real-time rail", d:"Or straight to a wallet or card via Send."},
   {at:"u-con", t:"The recipient has the money", d:"Often within seconds."},
  ]},
 {id:"b2b", g:"money", name:"A B2B virtual-card payment", why:"Commercial payments are the largest untapped flow — invoices worth ~$63tn a year — and virtual cards are how Mastercard is moving them onto the network.",
  scale:"Commercial is 38% of GDV; virtual cards run in 43 countries and 174 currencies with fraud under one-fifth of physical cards.", src:[["Commercial Connect / In Control expansion, Jul 2026","https://www.mastercard.com/us/en/news-and-trends/press/2026/july/Mastercard-expands-virtual-card-platform.html"],["Investor Day 2024 (PDF)","https://s25.q4cdn.com/479285134/files/doc_events/2024-Mastercard-Investment-Community-Presentation.pdf"]],
  steps:[
   {at:"u-corp", t:"A buyer's AP system approves an invoice", d:"Inside SAP, Emburse or a bank portal."},
   {at:"4.5", p:"incontrol", t:"Commercial Connect creates a virtual card with controls", d:"Amount, validity window and merchant category set at creation."},
   {at:"4.5", p:"bpc", t:"Business Payment Controls enforce the limits", d:"At authorisation and at clearing."},
   {at:"4.5", p:"trackbps", t:"Track BPS presents the payment to the supplier", d:"With terms and remittance data."},
   {at:"2.1", p:"cardscommercial", t:"Rides the commercial card rail", d:""},
   {at:"1.1", p:"swcore", t:"The switch routes to the issuing bank", d:""},
   {at:"u-iss", t:"The issuer approves", d:""},
   {at:"4.5", p:"receivables", t:"Receivables Manager reconciles it at the supplier", d:"Straight into the ERP."},
   {at:"4.5", p:"cen", t:"Commercial Event Notifications confirm both sides", d:""},
  ]},
 {id:"stable", g:"money", name:"Settling in stablecoins", why:"The newest rail: regulated stablecoins as a settlement currency for acquirers and issuers, with BVNK bridging on-chain and fiat.",
  scale:"Six regulated stablecoins across eight chains as of June 2026; stablecoin-funded cards already spend at 150m+ merchant locations; BVNK acquired for up to $1.8bn.", src:[["Stablecoin settlement expansion, Jun 2026","https://www.mastercard.com/global/en/news-and-trends/press/2026/june/mastercard-expands-settlement-capabilities-to-include-stablecoin.html"],["Stablecoin utility and scale, 2025","https://www.mastercard.com/us/en/news-and-trends/stories/2025/mastercard-stablecoin-utility-and-scale.html"]],
  steps:[
   {at:"u-acq", t:"An acquirer opts to settle in a stablecoin", d:"USDC, PYUSD, USDG, USDP, RLUSD or SoFiUSD."},
   {at:"1.1", p:"swcore", t:"Card transactions switch exactly as before", d:"Nothing changes at the point of sale."},
   {at:"2.4", p:"stable", t:"Settlement is made on-chain", d:"Intraday and weekend windows, not just banking days."},
   {at:"2.4", p:"mtn", t:"The Multi-Token Network moves tokenised value", d:"Interoperating with J.P. Morgan's Kinexys."},
   {at:"2.4", p:"bvnk", t:"BVNK bridges on-chain and fiat", d:"Chain-agnostic on- and off-ramps in 130+ countries."},
   {at:"4.1", p:"cryptosecure", t:"Crypto Secure scores the VASP counterparties", d:""},
   {at:"u-fin", t:"Funds land in the acquirer's wallet", d:""},
  ]},

 {id:"scam", g:"trust", name:"Stopping a scam on a real-time rail", why:"Authorised push-payment fraud is the fastest-growing loss in real-time payments. Mastercard scores the payment for the sending bank before it leaves.",
  scale:"Consumer Fraud Risk cut UK APP fraud by ~20% in 2024; A2A Protect now covers 15 UK banks (~90% of A2A volume).", src:[["A2A Protect, 2025","https://www.mastercard.com/news/europe/en-uk/newsroom/press-releases/en-gb/2025/prevent-protect-and-recover-mastercard-strengthens-trust-in-account-to-account-payments/"],["Consumer Fraud Risk expansion, Sep 2024","https://www.mastercard.com/us/en/news-and-trends/press/2024/september/mastercard-expands-first-of-its-kind-ai-technology-to-help-banks-protect-more-consumers-from-scams-in-real-time.html"]],
  steps:[
   {at:"u-con", t:"A victim is talked into sending money", d:"An 'investment', a fake invoice, a romance scam."},
   {at:"2.2", p:"fps", t:"They initiate a Faster Payment from their bank app", d:"Irrevocable once sent."},
   {at:"4.1", p:"a2aprotect", t:"A2A Protect scores the payment in real time", d:"Sender, receiver and network patterns, in seconds."},
   {at:"4.1", p:"trace", t:"TRACE flags the receiving account as a likely mule", d:"Newly created, unusual inflows."},
   {at:"u-iss", t:"The sending bank warns, holds or blocks", d:""},
   {at:"2.2", p:"vocalink", t:"If it did go, Recover runs a cross-bank return", d:"Standardised recovery over the Vocalink rail."},
  ]},
 {id:"dispute", g:"trust", name:"A disputed charge", why:"Most disputes are confusion, not fraud. The map's post-transaction services exist to resolve them before a chargeback — and to prove it when it's friendly fraud.",
  scale:"39m chargebacks prevented by Ethoca in 2025; First-Party Trust expanded to new markets in June 2025.", src:[["Ethoca Alerts","https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/dispute-management/ethoca-alerts.html"],["First-Party Trust expansion, Jun 2025","https://www.mastercard.com/us/en/news-and-trends/press/2025/june/first-party-trust-countering-friendly-fraud.html"]],
  steps:[
   {at:"u-con", t:"A cardholder doesn't recognise a charge", d:"'CRV*ACME 4471'?"},
   {at:"3.4", p:"merchantid", t:"Merchant Identifier resolves the name", d:"And Consumer Clarity shows the receipt in the app."},
   {at:"u-iss", t:"The issuer's app answers most questions on the spot", d:""},
   {at:"3.4", p:"ethocaalerts", t:"If it's fraud, Ethoca alerts the merchant to refund", d:"Before a chargeback is filed."},
   {at:"3.4", p:"mastercom", t:"Otherwise Mastercom manages the chargeback", d:"Pre-arbitration and arbitration under scheme rules."},
   {at:"3.4", p:"fpt", t:"First-Party Trust shifts liability when the evidence shows friendly fraud", d:""},
   {at:"3.3", p:"fld", t:"Confirmed fraud is recorded in FLD", d:"And feeds back into everyone's risk models."},
  ]},
 {id:"threat", g:"trust", name:"From cyber threat to blocked fraud", why:"Fraud rarely starts at the point of transaction; it starts as a cyberattack. Recorded Future was bought to close that gap.",
  scale:"Recorded Future indexes 1m+ sources; its 2025 report tracked 10,500 active digital-skimming (Magecart) infections.", src:[["Mastercard Threat Intelligence launch, Oct 2025","https://www.mastercard.com/us/en/news-and-trends/press/2025/october/Mastercard-introduces-first-ever-threat-intelligence-solution.html"],["Recorded Future annual payment fraud report","https://www.mastercard.com/us/en/news-and-trends/stories/2026/recorded-future-annual-payment-fraud-report.html"]],
  steps:[
   {at:"u-mer", t:"A merchant's checkout page is compromised", d:"A digital skimmer starts harvesting card numbers."},
   {at:"4.1", p:"recfut", t:"Recorded Future spots the skimmer and the cards on sale", d:"Dark-web listings and infected sites, indexed continuously."},
   {at:"4.1", p:"mcti", t:"Threat Intelligence turns it into fraud signals", d:"Card-testing rules and merchant threat assessments."},
   {at:"3.3", p:"odd", t:"On-Demand Decisioning blocks the card-testing attempts", d:"Rules on the network, before the issuer sees them."},
   {at:"3.3", p:"dipro", t:"Decision Intelligence Pro scores the rest", d:"Graph AI across merchants, not one at a time."},
   {at:"3.3", p:"fld", t:"Confirmed fraud is recorded in FLD", d:""},
   {at:"4.1", p:"riskrecon", t:"RiskRecon rates the merchant's cyber posture", d:"So the acquirer can act."},
  ]},
 {id:"outage", g:"trust", name:"An issuer goes down", why:"Resilience is a product. When an issuer's host fails, the kernel answers for it so cardholders keep paying.",
  scale:"Stand-In Authorization and Stand-In risk-based authentication run on the network for every issuer that enables them.", src:[["Payment resiliency","https://www.mastercard.com/global/en/business/cybersecurity-fraud-prevention/cybersecurity/on-demand-decisioning.html"]],
  steps:[
   {at:"u-iss", t:"An issuer's authorisation host stops responding", d:""},
   {at:"1.1", p:"standin", t:"Stand-In Authorization answers on its behalf", d:"Using the issuer's pre-agreed parameters."},
   {at:"3.3", p:"obrs", t:"On-Behalf Rules keep fraud controls in place", d:"Mastercard-managed rule cartridges."},
   {at:"3.2", p:"smartauth", t:"Stand-In RBA keeps 3-D Secure frictionless", d:"When the issuer's ACS is also down."},
   {at:"u-con", t:"Cardholders never notice", d:""},
  ]},

 {id:"agent", g:"frontier", name:"An AI agent buys on your behalf", why:"Agentic commerce needs a way to know which agent is acting, for whom, and within what authorisation. That is what Agent Pay adds to the stack.",
  scale:"First live authenticated agentic transaction in Hong Kong, 27 March 2026 (HSBC, DBS, CardInfoLink, hoppa), following Australia, Singapore, India and others.", src:[["First live agentic transaction, Hong Kong, Mar 2026","https://www.mastercard.com/news/ap/en-hk/newsroom/press-releases/en-hk/2026/mastercard-completes-its-first-live-agentic-transaction-in-hong-kong/"],["Agent Pay unveiled, Apr 2025","https://www.mastercard.com/global/en/news-and-trends/press/2025/april/mastercard-unveils-agent-pay-pioneering-agentic-payments-technology-to-power-commerce-in-the-age-of-ai.html"]],
  steps:[
   {at:"u-ai", t:"An agent is given a task", d:"'Book me a ride to the airport.'"},
   {at:"3.6", p:"kya", t:"Know Your Agent has registered it", d:"Only vetted, traceable agents can hold tokens."},
   {at:"3.6", p:"vintent", t:"Agentic Token + Verifiable Intent", d:"Proof the agent acted within your authorisation."},
   {at:"3.2", p:"passkeys", t:"You confirm with a Payment Passkey", d:"Explicit consent, captured once."},
   {at:"3.6", p:"agentpay", t:"Agent Pay initiates the payment", d:""},
   {at:"5.2", p:"merchantcloud", t:"Merchant Cloud accepts an agent-initiated payment", d:"The merchant can see it is an agent — and which one."},
   {at:"1.1", p:"swcore", t:"The switch routes to the issuer", d:""},
   {at:"3.3", p:"dipro", t:"Decision Intelligence Pro scores it with agent-level traceability", d:""},
   {at:"u-iss", t:"The issuer approves", d:""},
   {at:"3.4", p:"ethocacc", t:"Consumer Clarity shows exactly what the agent bought", d:""},
  ]},
 {id:"machine", g:"frontier", name:"Machines paying machines", why:"The step after agents: devices and services paying each other in high-frequency micro-payments, across cards, accounts and stablecoins.",
  scale:"Agent Pay for Machines launched June 2026 with 30+ partners including Stripe, Adyen, Coinbase and the Solana Foundation.", src:[["Agent Pay for Machines launch, Jun 2026","https://www.mastercard.com/global/en/news-and-trends/press/2026/june/mastercard-launches-agent-pay-for-machines.html"]],
  steps:[
   {at:"u-ai", t:"A device needs to buy something", d:"Compute, data, charging, a toll — many times an hour."},
   {at:"3.6", p:"ap4m", t:"Agent Pay for Machines credentials and permissions it", d:"Spend rules set by the owner."},
   {at:"3.6", p:"kya", t:"Know Your Agent verifies the machine's identity", d:""},
   {at:"2.4", p:"stable", t:"Settles over cards, accounts or stablecoins", d:"Whichever rail fits the size and speed."},
   {at:"1.1", p:"swcore", t:"Through the kernel like any other flow", d:""},
   {at:"u-corp", t:"The supplier's machine is paid", d:"Reconciled automatically."},
  ]},
 {id:"onecred", g:"frontier", name:"One card, many ways to pay", why:"Mastercard's answer to 'why do I need three cards?': one credential, issued instantly, with debit, credit, prepaid and instalments behind it and a passkey instead of passwords.",
  scale:"One Credential partners include Wio Bank, Marqeta, Lithic and Botim (Aug 2026); Digital First issuers see +8% tokenised and +10% contactless transactions.", src:[["One Credential","https://www.mastercard.com/global/en/business/payments/consumer-payments/next-gen-payments/mastercard-one-credential.html"],["Digital First","https://www.mastercard.com/global/en/business/payments/consumer-payments/next-gen-payments/digital-first.html"]],
  steps:[
   {at:"u-con", t:"A new customer opens an account in-app", d:""},
   {at:"5.3", p:"processing", t:"Mastercard Processing issues the card instantly", d:"Or the issuer's own processor, via Cloud Edge."},
   {at:"3.1", p:"digitalfirst", t:"Digital First: usable before the plastic arrives", d:""},
   {at:"3.1", p:"onecred", t:"One Credential links debit, credit, prepaid and instalments", d:"The customer sets which to use when."},
   {at:"3.1", p:"mdes", t:"MDES tokenises it into the wallet", d:""},
   {at:"3.2", p:"passkeys", t:"Checkout confirms with a passkey", d:"No OTPs."},
   {at:"2.1", p:"installments", t:"A big purchase is split into instalments", d:"Same credential, different funding."},
   {at:"u-iss", t:"The issuer sees one customer, not three cards", d:""},
  ]},
 {id:"lend", g:"frontier", name:"Open-finance-powered lending", why:"Consumer-permissioned bank data replaces paperwork: verify the applicant, read their cash flow, decide — and move their payroll to the new account.",
  scale:"Open Finance US reaches ~95% of US deposit accounts; Open Finance Europe connects to ~3,000 banks.", src:[["Open Finance (US)","https://www.mastercard.com/us/en/business/open-finance.html"],["Open Finance (Europe) — Developers","https://developer.mastercard.com/product/open-finance-europe"]],
  steps:[
   {at:"u-con", t:"An applicant applies for a loan", d:"On their phone, in minutes."},
   {at:"2.6", p:"dataconnect", t:"Data Connect captures consent to share bank data", d:""},
   {at:"2.6", p:"ofus", t:"Open Finance verifies accounts, owner, income and assets", d:"Finicity in the US, Aiia in Europe."},
   {at:"4.1", p:"mcidentity", t:"Identity Insights checks the applicant is who they say", d:""},
   {at:"4.3", p:"creditintel", t:"Credit Intelligence scores the cash flow", d:"Alternative data for thin-file applicants."},
   {at:"u-iss", t:"The lender decides", d:""},
   {at:"2.6", p:"ofus", t:"Deposit Switch moves payroll to the new account", d:"Bill Pay Switch updates the billers."},
  ]},
 {id:"inclusion", g:"frontier", name:"A smallholder farmer gets paid", why:"Community Pass takes the same stack to places with no connectivity and no bank: a digital identity, an offline-capable credential and a disbursement rail.",
  scale:"MADE Alliance: Africa targets 100m people and businesses by 2034; Mastercard's Africa acceptance network grew 45% in 2025.", src:[["Community Pass","https://www.mastercard.com/europe/en/for-the-world/prosperity/community-pass.html"],["Africa acceptance +45%, Dec 2025","https://www.mastercard.com/news/eemea/en/newsroom/press-releases/en/2025-1/december/mastercard-boosts-africa-acceptance-network-by-45-in-2025-accelerating-the-continent-s-digital-economy/"]],
  steps:[
   {at:"u-gov", t:"A cooperative or agency registers farmers", d:"Often offline, in the field."},
   {at:"pillar-inclusion", p:"communitypass", t:"Community Pass issues a digital ID and Farm Pass record", d:"Biometric, with IDEMIA."},
   {at:"u-corp", t:"An agri-buyer purchases the harvest", d:""},
   {at:"2.3", p:"disb", t:"Payment is disbursed through Move", d:"To a card, account or wallet."},
   {at:"2.1", p:"cardsconsumer", t:"Or onto a prepaid card that works offline", d:""},
   {at:"u-con", t:"The farmer is paid — and has a record", d:"Which becomes a credit history."},
  ]},
];
